# Sjednocení a technické čištění dat

Cílem notebooku je sjednotit výstupy jednotlivých parserů do jedné konzistentní datové sady. V této fázi se neprovádí jazykové předzpracování textu pro výpočet podobnosti, například tokenizace, lemmatizace, odstranění stop slov nebo vektorizace. Tyto kroky budou řešeny až v metodice porovnávání sylabů.

Notebook se zaměřuje na kontrolu schématu, sjednocení prázdných hodnot, technické čištění textových polí, kontrolu formálních atributů a export výsledných CSV souborů do složky `data/processed`.

In [1]:
# standardní knihovny Pythonu
import sys
import re
from pathlib import Path

# knihovny třetích stran
import pandas as pd
import numpy as np

# nastavení root složky projektu pro import utility modulů
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

# sdílené schéma datasetu
from utils.schema import FINAL_COLUMNS

# nastavení cest ve struktuře projektu
INTERIM_DIR = PROJECT_ROOT / "data" / "interim"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

# vytvoření výstupní složky, pokud neexistuje
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# nastavení zobrazení dataframe
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)

## Načtení parsed datasetů a kontrola schématu

In [2]:
# seznam parsed datasetů
DATASETS = {
    "vse": "vse_syllabi_raw_parsed.csv",
    "bi": "bi_syllabi_raw_parsed.csv",
    "canterbury": "canterbury_syllabi_raw_parsed.csv",
    "edinburgh": "edinburgh_syllabi_raw_parsed.csv",
    "hkust": "hkust_syllabi_raw_parsed.csv",
    "itam": "itam_syllabi_raw_parser.csv",
    "queens": "queens_syllabi_raw_parsed.csv"
}

# načtení datasetů do dictionary
dfs = {}

for name, filename in DATASETS.items():

    file_path = INTERIM_DIR / filename

    df = pd.read_csv(file_path)

    # kontrola shody schématu
    missing_columns = set(FINAL_COLUMNS) - set(df.columns)
    extra_columns = set(df.columns) - set(FINAL_COLUMNS)

    print(f"\n{name.upper()}")

    if missing_columns:
        print(f"Chybějící sloupce: {missing_columns}")

    if extra_columns:
        print(f"Nadbytečné sloupce: {extra_columns}")

    if not missing_columns and not extra_columns:
        print("Schéma odpovídá.")

    # seřazení sloupců podle jednotného schématu
    df = df[FINAL_COLUMNS]

    dfs[name] = df

VSE
Schéma odpovídá.

BI
Schéma odpovídá.

CANTERBURY
Schéma odpovídá.

EDINBURGH
Schéma odpovídá.

HKUST
Schéma odpovídá.

ITAM
Schéma odpovídá.

QUEENS
Schéma odpovídá.

## Vytvoření hlavních datasetů

In [3]:
# referenční dataset sylabů VŠE
vse_df = dfs["vse"].copy()

# spojení datasetů partnerských univerzit
partner_df = pd.concat(
    [
        dfs["bi"],
        dfs["canterbury"],
        dfs["edinburgh"],
        dfs["hkust"],
        dfs["itam"],
        dfs["queens"]
    ],
    ignore_index=True
)

# kontrola velikosti datasetů
print(f"VŠE dataset: {len(vse_df)} záznamů")
print(f"Partnerský dataset: {len(partner_df)} záznamů")

VŠE dataset: 133 záznamů
Partnerský dataset: 936 záznamů

## Základní přehled hlavních datasetů

In [4]:
# základní přehled hlavních datasetů
overview_df = pd.DataFrame([
    {
        "dataset": "vse",
        "rows": len(vse_df),
        "columns": len(vse_df.columns),
        "missing_course_title": vse_df["course_title"].isna().sum(),
        "missing_course_code": vse_df["course_code"].isna().sum()
    },
    {
        "dataset": "partners",
        "rows": len(partner_df),
        "columns": len(partner_df.columns),
        "missing_course_title": partner_df["course_title"].isna().sum(),
        "missing_course_code": partner_df["course_code"].isna().sum()
    }
])

overview_df

    dataset  rows  columns  missing_course_title  missing_course_code
0       vse   133       17                     0                    0
1  partners   936       17                     0                    0

## Základní sjednocení textových polí

In [5]:
# textové sloupce datasetu
TEXT_COLUMNS = [
    "course_title",
    "course_code",
    "university",
    "country",
    "source_url",
    "academic_year",
    "semester",
    "semester_normalized",
    "study_level",
    "credit_system",
    "aims",
    "course_content",
    "learning_outcomes",
    "assessment_methods",
    "literature"
]

# základní technické čištění textových polí
for df in [vse_df, partner_df]:

    for column in TEXT_COLUMNS:

        # převod na string datatype
        df[column] = df[column].astype("string")

        # odstranění nadbytečných whitespace znaků
        df[column] = (
            df[column]
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

## Kontrola sloupce `course_title`

In [6]:
# základní kontrola názvů předmětů
course_title_summary = pd.DataFrame([
    {
        "dataset": "vse",
        "missing_values": vse_df["course_title"].isna().sum()
    },
    {
        "dataset": "partners",
        "missing_values": partner_df["course_title"].isna().sum()
    }
])

course_title_summary

    dataset  missing_values
0       vse               0
1  partners               0

## Kontrola sloupce `course_code`

In [7]:
# základní kontrola kódů předmětů
course_code_summary = pd.DataFrame([
    {
        "dataset": "vse",
        "missing_values": vse_df["course_code"].isna().sum(),
        "unique_values": vse_df["course_code"].nunique(),
        "duplicated_values": vse_df["course_code"].duplicated().sum()
    },
    {
        "dataset": "partners",
        "missing_values": partner_df["course_code"].isna().sum(),
        "unique_values": partner_df["course_code"].nunique(),
        "duplicated_values": partner_df["course_code"].duplicated().sum()
    }
])

course_code_summary

    dataset  missing_values  unique_values  duplicated_values
0       vse               0            133                  0
1  partners               0            903                 33

In [8]:
# počet duplicitních kódů podle univerzit
duplicate_course_codes_summary = (
    partner_df[partner_df["course_code"].duplicated(keep=False)]
    .groupby("university")["course_code"]
    .nunique()
    .reset_index(name="duplicate_course_codes")
    .sort_values("duplicate_course_codes", ascending=False)
)

duplicate_course_codes_summary

                university  duplicate_course_codes
0       Queen's University                      32
1  University of Edinburgh                       1

In [9]:
# kontrola úplných duplicitních řádků podle univerzit
full_duplicate_rows = (
    partner_df[partner_df.duplicated(keep=False)]
    .groupby("university")
    .size()
    .reset_index(name="full_duplicate_rows")
    .sort_values("full_duplicate_rows", ascending=False)
)

full_duplicate_rows

                university  full_duplicate_rows
0  University of Edinburgh                    2

In [10]:
# kontrola duplicit na Queen's University po ignorování semestru
queens_df = partner_df[
    partner_df["university"] == "Queen's University"
].copy()

compare_columns_without_semester = [
    column for column in FINAL_COLUMNS
    if column not in ["semester", "semester_normalized"]
]

queens_duplicates_without_semester = (
    queens_df
    .drop(columns=["semester", "semester_normalized"])
    .duplicated()
    .sum()
)

queens_problematic_codes = (
    queens_df
    .groupby("course_code")[compare_columns_without_semester]
    .nunique(dropna=False)
)

queens_problematic_codes = queens_problematic_codes[
    (queens_problematic_codes > 1).any(axis=1)
].index.tolist()

print(
    f"Počet duplicitních řádků na Queen's po ignorování semestru: "
    f"{queens_duplicates_without_semester}"
)

print(
    f"Kódy s rozdílem i mimo semestr: {queens_problematic_codes}"
)

Počet duplicitních řádků na Queen's po ignorování semestru: 31
Kódy s rozdílem i mimo semestr: ['COMM 321']

In [11]:
# kontrola rozdílů u výjimky COMM 321
comm_321 = queens_df[
    queens_df["course_code"] == "COMM 321"
].copy()

comm_321_diff = (
    comm_321[compare_columns_without_semester]
    .nunique(dropna=False)
    .reset_index()
)

comm_321_diff.columns = ["column", "unique_values"]

comm_321_diff[
    comm_321_diff["unique_values"] > 1
]

         column  unique_values
0  course_title              2

In [12]:
# hodnoty rozdílného názvu u COMM 321
comm_321[
    ["course_code", "course_title", "semester", "semester_normalized"]
]

,course_code,course_title,semester,semester_normalized
850,COMM 321,Derivative Securities (equivalent to ),Fall,winter
903,COMM 321,Derivative Securities,Winter,summer

### Rozhodnutí k duplicitám ve sloupci `course_code`

Kontrola ukázala, že úplná duplicita řádku se vyskytuje u University of Edinburgh. U Queen's University jsou duplicity způsobeny tím, že stejné předměty jsou uvedeny pro semestry Fall a Winter. Po ignorování sloupců `semester` a `semester_normalized` jsou záznamy shodné. Výjimkou je předmět `COMM 321`, u kterého se mimo semestr liší pouze hodnota ve sloupci `course_title`. Jelikož jde o stejný kód předmětu a název se liší jen doplňující poznámkou v jedné z variant, byl i tento případ vyhodnocen jako duplicitní záznam. Vzhledem k tomu, že cílem datové sady je reprezentovat sylabus předmětu, nikoliv každé semestrální vypsání zvlášť, bude pro Queen's University ponechána pouze varianta Winter, která odpovídá novější verzi v akademickém roce 2025/2026.

In [13]:
# odstranění úplných duplicitních řádků
partner_df = partner_df.drop_duplicates().reset_index(drop=True)

# odstranění duplicit u Queen's University se zachováním varianty Winter
queens_mask = partner_df["university"] == "Queen's University"

queens_clean = (
    partner_df[queens_mask]
    .assign(
        semester_priority=lambda df: df["semester"].eq("Winter").astype(int)
    )
    .sort_values(
        by=["course_code", "semester_priority"],
        ascending=[True, False]
    )
    .drop_duplicates(
        subset=["course_code"],
        keep="first"
    )
    .drop(columns=["semester_priority"])
)

# složení partnerského datasetu po deduplikaci
partner_df = pd.concat(
    [
        partner_df[~queens_mask],
        queens_clean
    ],
    ignore_index=True
)

# kontrola duplicit po čištění
partner_df[
    partner_df.duplicated(
        subset=["university", "course_code"],
        keep=False
    )
]

Empty DataFrame
Columns: [course_title, course_code, university, country, source_url, academic_year, semester, semester_normalized, study_level, credits, credit_system, ects_credits, aims, course_content, learning_outcomes, assessment_methods, literature]
Index: []

## Kontrola sloupce `university`

In [14]:
# kontrola názvů univerzit
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["university"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["university"].nunique())

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["university"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["university"].nunique())

print("\nUniverzity v partnerském datasetu:")

sorted(partner_df["university"].unique())

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 1

Partneři
Chybějící hodnoty: 0
Počet unikátních hodnot: 6

Univerzity v partnerském datasetu:

['BI Norwegian Business School',
 'Instituto Tecnológico Autónomo de México',
 "Queen's University",
 'The Hong Kong University of Science and Technology',
 'University of Canterbury',
 'University of Edinburgh']

## Kontrola sloupce `country`

In [15]:
# kontrola názvů zemí
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["country"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["country"].nunique())

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["country"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["country"].nunique())

print("\nZemě v partnerském datasetu:")

sorted(partner_df["country"].unique())

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 1

Partneři
Chybějící hodnoty: 0
Počet unikátních hodnot: 6

Země v partnerském datasetu:

['Canada', 'Hong Kong', 'Mexico', 'New Zealand', 'Norway', 'United Kingdom']

## Kontrola sloupce `source_url`

In [16]:
# kontrola URL adres zdrojů
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["source_url"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["source_url"].nunique())

print("Duplicitní hodnoty:",
      vse_df["source_url"].duplicated().sum())

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["source_url"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["source_url"].nunique())

print("Duplicitní hodnoty:",
      partner_df["source_url"].duplicated().sum())

print("\nDuplicitní URL podle univerzit:")

(
    partner_df[
        partner_df["source_url"].duplicated(keep=False)
    ]
    .groupby("university")["source_url"]
    .nunique()
    .reset_index(name="duplicate_source_urls")
    .sort_values("duplicate_source_urls", ascending=False)
)

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 133
Duplicitní hodnoty: 0

Partneři
Chybějící hodnoty: 0
Počet unikátních hodnot: 501
Duplicitní hodnoty: 402

Duplicitní URL podle univerzit:

                                           university  duplicate_source_urls
1  The Hong Kong University of Science and Technology                     12
0            Instituto Tecnológico Autónomo de México                      1

In [17]:
# výpis duplicitních URL u HKUST
sorted(
    partner_df[
        (
            partner_df["university"] ==
            "The Hong Kong University of Science and Technology"
        )
        &
        (
            partner_df["source_url"].duplicated(keep=False)
        )
    ]["source_url"]
    .drop_duplicates()
    .tolist()
)

['https://prog-crs.hkust.edu.hk/ugcourse/2025-26/ACCT',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/COMP',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/DASC',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/ECON',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/ENTR',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/FINA',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/GBUS',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/ISOM',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/MARK',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/MATH',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/MGMT',
 'https://prog-crs.hkust.edu.hk/ugcourse/2025-26/RMBI']

U sloupce `source_url` byly identifikovány duplicitní hodnoty zejména u Instituto Tecnológico Autónomo de México, kde všechny předměty odkazují na společný zdrojový dokument obsahující více sylabů. Menší počet duplicit se vyskytoval také u The Hong Kong University of Science and Technology. Kontrola ukázala, že tyto URL odpovídají stránkám jednotlivých předmětových oblastí definovaných prefixem kódu předmětu (např. ACCT, COMP, ISOM nebo MATH). Jednotlivé předměty byly na těchto stránkách dostupné jako rozbalitelné sekce v rámci jedné společné URL adresy, nikoliv jako samostatné detailní stránky. Duplicitní URL adresy proto byly vyhodnoceny jako očekávaná vlastnost zdrojových dat a nebyly dále upravovány.

## Kontrola sloupce `academic_year`

In [18]:
# kontrola akademických roků
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["academic_year"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["academic_year"].nunique())

print("\nPočty řádků podle academic_year:")

print(
    vse_df["academic_year"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["academic_year"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["academic_year"].nunique())

print("\nPočty řádků podle academic_year:")

print(
    partner_df["academic_year"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 2

Počty řádků podle academic_year:
academic_year
2025/2026    55
2026/2027    78
Name: count, dtype: Int64

Partneři
Chybějící hodnoty: 0
Počet unikátních hodnot: 13

Počty řádků podle academic_year:
academic_year
2015-2016      1
2016-2017      3
2018-2019      1
2019           1
2019-2020      2
2023-2024      3
2024          39
2024-2025     22
2025          49
2025-2026     71
2025-26      382
2025/26       98
2026         231
Name: count, dtype: Int64

### Sjednocení formátu akademického roku

In [19]:
# sjednocení formátu academic_year
def normalize_academic_year(row):

    year = str(row["academic_year"]).strip()

    semester = (
        str(row["semester_normalized"])
        .strip()
        .lower()
    )

    # formát 2025-2026 nebo 2025/2026
    match_full = re.match(
        r"^(\d{4})[-/](\d{4})$",
        year
    )

    if match_full:

        return (
            f"{match_full.group(1)}"
            f"/{match_full.group(2)}"
        )

    # formát 2025-26 nebo 2025/26
    match_short = re.match(
        r"^(\d{4})[-/](\d{2})$",
        year
    )

    if match_short:

        start_year = int(match_short.group(1))

        end_year = int(
            str(start_year)[:2] +
            match_short.group(2)
        )

        return f"{start_year}/{end_year}"

    # formát s jedním rokem
    match_single = re.match(
        r"^(\d{4})$",
        year
    )

    if match_single:

        year_value = int(match_single.group(1))

        # winter = začátek akademického roku
        if semester == "winter":

            return (
                f"{year_value}"
                f"/{year_value + 1}"
            )

        # summer = konec akademického roku
        if semester == "summer":

            return (
                f"{year_value - 1}"
                f"/{year_value}"
            )

    # ostatní hodnoty ponecháme beze změny
    return year

# aplikace normalizace
vse_df["academic_year"] = (
    vse_df.apply(
        normalize_academic_year,
        axis=1
    )
)

partner_df["academic_year"] = (
    partner_df.apply(
        normalize_academic_year,
        axis=1
    )
)

# kontrola výsledných hodnot
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["academic_year"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["academic_year"].nunique())

print("\nPočty řádků podle academic_year:")

print(
    vse_df["academic_year"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["academic_year"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["academic_year"].nunique())

print("\nPočty řádků podle academic_year:")

print(
    partner_df["academic_year"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 2

Počty řádků podle academic_year:
academic_year
2025/2026    55
2026/2027    78
Name: count, dtype: int64

Partneři
Chybějící hodnoty: 0
Počet unikátních hodnot: 9

Počty řádků podle academic_year:
academic_year
2015/2016      1
2016/2017      3
2018/2019      1
2019           1
2019/2020      2
2023/2024      3
2024/2025     76
2025/2026    690
2026/2027    126
Name: count, dtype: int64

Hodnoty ve sloupci `academic_year` byly sjednoceny do formátu `YYYY/YYYY`. U hodnot obsahujících pouze jeden rok byl akademický rok dopočten pouze v případech, kdy byl dostupný normalizovaný semestr. Hodnoty bez dostatečného kontextu nebyly automaticky upravovány.

## Kontrola sloupce `semester`

In [20]:
# kontrola hodnot semester
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["semester"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["semester"].nunique())

print("\nPočty řádků podle semester:")

print(
    vse_df["semester"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["semester"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["semester"].nunique())

print("\nPočty řádků podle semester:")

print(
    partner_df["semester"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 2

Počty řádků podle semester:
semester
WS 2025/2026    55
WS 2026/2027    78
Name: count, dtype: Int64

Partneři
Chybějící hodnoty: 384
Počet unikátních hodnot: 11

Počty řádků podle semester:
semester
Autumn           73
Fall             58
Full Year         2
Semester 1       44
Semester 2       52
Semester One    104
Semester Two     88
Spring           16
Winter           51
fall             26
spring            5
<NA>            384
Name: count, dtype: Int64

In [21]:
# sjednocení velikosti písmen u semester
partner_df["semester"] = (
    partner_df["semester"]
    .replace({
        "fall": "Fall",
        "spring": "Spring"
    })
)

# kontrola výsledných hodnot
partner_df["semester"].value_counts(
    dropna=False
).sort_index()

semester
Autumn           73
Fall             84
Full Year         2
Semester 1       44
Semester 2       52
Semester One    104
Semester Two     88
Spring           21
Winter           51
<NA>            384
Name: count, dtype: Int64

U sloupce `semester` byly sjednoceny pouze rozdíly ve velikosti písmen u hodnot `Fall` a `Spring`. Ostatní varianty byly ponechány v podobě publikované zdrojovou institucí.

## Kontrola sloupce `semester_normalized`

In [22]:
# kontrola hodnot semester_normalized
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["semester_normalized"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["semester_normalized"].nunique())

print("\nPočty řádků podle semester_normalized:")

print(
    vse_df["semester_normalized"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["semester_normalized"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["semester_normalized"].nunique())

print("\nPočty řádků podle semester_normalized:")

print(
    partner_df["semester_normalized"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 1

Počty řádků podle semester_normalized:
semester_normalized
winter    133
Name: count, dtype: Int64

Partneři
Chybějící hodnoty: 384
Počet unikátních hodnot: 3

Počty řádků podle semester_normalized:
semester_normalized
full_year      2
summer       228
winter       289
<NA>         384
Name: count, dtype: Int64

Sloupec `semester_normalized` obsahuje sjednocenou reprezentaci semestru napříč institucemi. Hodnoty byly mapovány na kategorie `winter`, `summer` a `full_year`. Chybějící hodnoty odpovídají případům, kdy zdrojová data informaci o semestru neobsahovala.

## Kontrola sloupce `study_level`

In [23]:
# kontrola hodnot study_level
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["study_level"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["study_level"].nunique())

print("\nPočty řádků podle study_level:")

print(
    vse_df["study_level"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["study_level"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["study_level"].nunique())

print("\nPočty řádků podle study_level:")

print(
    partner_df["study_level"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 2

Počty řádků podle study_level:
study_level
bachelor    124
master        9
Name: count, dtype: Int64

Partneři
Chybějící hodnoty: 0
Počet unikátních hodnot: 4

Počty řádků podle study_level:
study_level
Bachelor          56
Master            71
Undergraduate     98
undergraduate    678
Name: count, dtype: Int64

In [24]:
# sjednocení velikosti písmen u study_level
STUDY_LEVEL_MAPPING = {
    "Bachelor": "bachelor",
    "Master": "master",
    "Undergraduate": "undergraduate"
}

vse_df["study_level"] = (
    vse_df["study_level"]
    .replace(STUDY_LEVEL_MAPPING)
)

partner_df["study_level"] = (
    partner_df["study_level"]
    .replace(STUDY_LEVEL_MAPPING)
)

# kontrola výsledných hodnot
print("VŠE")

print(
    vse_df["study_level"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")

print(
    partner_df["study_level"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
study_level
bachelor    124
master        9
Name: count, dtype: Int64

Partneři
study_level
bachelor          56
master            71
undergraduate    776
Name: count, dtype: Int64

U sloupce `study_level` byly sjednoceny pouze rozdíly ve velikosti písmen. Hodnoty reprezentující terminologii jednotlivých vzdělávacích systémů byly ponechány beze změny.

## Kontrola sloupce `credits`

In [25]:
# kontrola hodnot credits
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["credits"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["credits"].nunique())

print("\nPočty řádků podle credits:")

print(
    vse_df["credits"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["credits"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["credits"].nunique())

print("\nPočty řádků podle credits:")

print(
    partner_df["credits"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 6

Počty řádků podle credits:
credits
2      2
3     12
4     17
5     31
6     70
30     1
Name: count, dtype: int64

Partneři
Chybějící hodnoty: 0
Počet unikátních hodnot: 13

Počty řádků podle credits:
credits
0.0       1
1.0      38
2.0      12
3.0     318
4.0      80
5.0       1
6.0      68
7.5      91
8.0       2
15.0    193
20.0     96
30.0      1
40.0      2
Name: count, dtype: int64

In [26]:
# kontrola nestandardních hodnot credits
partner_df[
    partner_df["credits"].isin([0.0, 40.0])
][
    [
        "university",
        "course_code",
        "course_title",
        "credits",
        "credit_system",
        "ects_credits",
        "source_url"
    ]
]

,university,course_code,course_title,credits,credit_system,ects_credits,source_url
49,BI Norwegian Business School,FORK 2200,Preparatory Course in Programming,0.0,ECTS,0.0,https://programmeinfo.bi.no/nb/course/FORK-2200/2026-autumn
383,University of Edinburgh,ECNM08013,Economics 1,40.0,SCQF credits,20.0,https://www.drps.ed.ac.uk/25-26/dpt/cxecnm08013.htm
385,University of Edinburgh,ECNM08006,Economics 2,40.0,SCQF credits,20.0,https://www.drps.ed.ac.uk/25-26/dpt/cxecnm08006.htm

In [27]:
# odstranění nekreditovaného přípravného kurzu
partner_df = partner_df[
    partner_df["credits"] != 0
].reset_index(drop=True)

# sjednocení datového typu credits
vse_df["credits"] = (
    vse_df["credits"]
    .astype(float)
)

partner_df["credits"] = (
    partner_df["credits"]
    .astype(float)
)

# kontrola výsledných hodnot
print("VŠE")

print(
    vse_df["credits"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")

print(
    partner_df["credits"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
credits
2.0      2
3.0     12
4.0     17
5.0     31
6.0     70
30.0     1
Name: count, dtype: int64

Partneři
credits
1.0      38
2.0      12
3.0     318
4.0      80
5.0       1
6.0      68
7.5      91
8.0       2
15.0    193
20.0     96
30.0      1
40.0      2
Name: count, dtype: int64

U partnerských univerzit byl identifikován jeden předmět s hodnotou `0` ve sloupci `credits`. Kontrola zdrojového sylabu ukázala, že se jednalo o přípravný nekreditovaný kurz, nikoliv standardní akademický předmět. Záznam byl proto z datasetu odstraněn.

## Kontrola sloupce `credit_system`

In [28]:
# kontrola hodnot credit_system
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["credit_system"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["credit_system"].nunique())

print("\nPočty řádků podle credit_system:")

print(
    vse_df["credit_system"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["credit_system"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["credit_system"].nunique())

print("\nPočty řádků podle credit_system:")

print(
    partner_df["credit_system"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 1

Počty řádků podle credit_system:
credit_system
ECTS    133
Name: count, dtype: Int64

Partneři
Chybějící hodnoty: 0
Počet unikátních hodnot: 6

Počty řádků podle credit_system:
credit_system
ECTS             126
HKUST credits    382
ITAM credits      33
Queen's units     71
SCQF credits      98
UC points        192
Name: count, dtype: Int64

Sloupec `credit_system` byl ponechán beze změny. Hodnoty odpovídají kreditovým systémům používaným jednotlivými institucemi.

## Kontrola sloupce `ects_credits`

In [29]:
# kontrola hodnot ects_credits
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["ects_credits"].isna().sum())

print("Počet unikátních hodnot:",
      vse_df["ects_credits"].nunique())

print("\nPočty řádků podle ects_credits:")

print(
    vse_df["ects_credits"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["ects_credits"].isna().sum())

print("Počet unikátních hodnot:",
      partner_df["ects_credits"].nunique())

print("\nPočty řádků podle ects_credits:")

print(
    partner_df["ects_credits"]
    .value_counts(dropna=False)
    .sort_index()
)

VŠE
Chybějící hodnoty: 0
Počet unikátních hodnot: 6

Počty řádků podle ects_credits:
ects_credits
2      2
3     12
4     17
5     31
6     70
30     1
Name: count, dtype: int64

Partneři
Chybějící hodnoty: 0
Počet unikátních hodnot: 11

Počty řádků podle ects_credits:
ects_credits
2.0      38
4.0      12
5.0      31
6.0     351
7.0       2
7.5     282
8.0      80
10.0     97
12.0      4
15.0      3
20.0      2
Name: count, dtype: int64

In [30]:
# sjednocení datového typu ects_credits
vse_df["ects_credits"] = (
    vse_df["ects_credits"]
    .astype(float)
)

partner_df["ects_credits"] = (
    partner_df["ects_credits"]
    .astype(float)
)

# kontrola datových typů
print(vse_df["ects_credits"].dtype)

print(partner_df["ects_credits"].dtype)

float64
float64

In [31]:
# kontrola správnosti přepočtu na ECTS kredity
credit_check_df = partner_df.copy()

credit_check_df["credits_num"] = pd.to_numeric(
    credit_check_df["credits"],
    errors="coerce"
)

credit_check_df["ects_num"] = pd.to_numeric(
    credit_check_df["ects_credits"],
    errors="coerce"
)

def check_ects_conversion(row):

    university = row["university"]
    credits = row["credits_num"]
    ects = row["ects_num"]

    if pd.isna(credits) or pd.isna(ects):
        return False

    if university == "BI Norwegian Business School":
        expected = credits

    elif university == "The Hong Kong University of Science and Technology":
        expected = credits * 2

    elif university == "Instituto Tecnológico Autónomo de México":
        expected = round(credits * 5 / 6)

    elif university == "University of Canterbury":
        expected = credits / 2

    elif university == "Queen's University":
        expected = credits * 2

    elif university == "University of Edinburgh":
        expected = credits / 2

    else:
        return False

    return abs(expected - ects) < 0.01

credit_check_df["ects_conversion_correct"] = (
    credit_check_df
    .apply(check_ects_conversion, axis=1)
)

print("Počet správných přepočtů:")
print(
    credit_check_df["ects_conversion_correct"]
    .sum()
)

print("\nPočet nesprávných přepočtů:")
print(
    (~credit_check_df["ects_conversion_correct"])
    .sum()
)

print("\nNesprávné přepočty:")

display(
    credit_check_df[
        credit_check_df["ects_conversion_correct"] == False
    ][
        [
            "course_code",
            "course_title",
            "university",
            "credits",
            "ects_credits",
            "source_url"
        ]
    ]
)

Počet správných přepočtů:
902

Počet nesprávných přepočtů:
0

Nesprávné přepočty:

Empty DataFrame
Columns: [course_code, course_title, university, credits, ects_credits, source_url]
Index: []

Kontrola ukázala, že hodnoty ve sloupci `ects_credits` odpovídají převodním pravidlům definovaným pro jednotlivé kreditové systémy partnerských univerzit. Nebyly identifikovány žádné nekonzistentní přepočty.

## Kontrola sloupce `aims`

In [32]:
# kontrola hodnot aims
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["aims"].isna().sum())

print("Prázdné řetězce:",
      (vse_df["aims"].str.strip() == "").sum())

print("\nDélka textu:")

print(
    vse_df["aims"]
    .str.len()
    .describe()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["aims"].isna().sum())

print("Prázdné řetězce:",
      (partner_df["aims"].str.strip() == "").sum())

print("\nDélka textu:")

print(
    partner_df["aims"]
    .str.len()
    .describe()
)

VŠE
Chybějící hodnoty: 0
Prázdné řetězce: 0

Délka textu:
count         133.0
mean     347.180451
std      281.991184
min            22.0
25%           132.0
50%           304.0
75%           450.0
max          1526.0
Name: aims, dtype: Float64

Partneři
Chybějící hodnoty: 2
Prázdné řetězce: 0

Délka textu:
count         900.0
mean     549.474444
std      426.468519
min            26.0
25%          257.75
50%           462.0
75%          699.25
max          4931.0
Name: aims, dtype: Float64

In [33]:
# nejčastější začátky textů ve sloupci aims
print("VŠE")

display(
    vse_df["aims"]
    .str[:80]
    .value_counts()
    .head(15)
)

print("\nPartneři")

display(
    partner_df["aims"]
    .str[:80]
    .value_counts()
    .head(15)
)

VŠE

aims
The aims of the course has not been saved in this language version.                 27
-- item not defined --                                                               3
Accounting as an information tool for the decision-making of an entity’s owners,     3
The course focuses on the process of finding entrepreneurial opportunities, veri     2
The purpose is to teach students to think economically, to familiarize students      2
Students will learn the purpose of a business plan, its users, methods, techniqu     1
The aim of the course is that students get to know to the issue of marketing and     1
A good knowledge of the office pack is useful for students both for elaboration      1
With the growing integration of Czech enterprises into international cooperation     1
Students will get to know the possibilities of database systems, which are a par     1
Team collaboration software tools are playing increasingly important role in eve     1
The course is focused on the basics of company marketing management introducing      1
The class aims at understanding current economic situation in the world as well      1
The aim of the course is that students get familiar with business transactions t     1
The aim of the course is that students get to know basic institutes of commercia     1
Name: count, dtype: Int64

Partneři

aims
This special topic will allow flexibility to offer new or one-off courses of str    4
This is a project-based course that provides students an opportunity to integrat    4
Individual Course of Study                                                          3
Analysis of sequentially collected data including data modelling and forecasting    3
This intermediate level course is intended to develop a rigorous understanding o    2
This course is a supervised course which trains student to do proper economic re    2
Financial technology (Fintech) refers to the digitalization and technological in    2
An introduction to the ideas, techniques and applications of statistics and prob    2
The course covers basic applications and techniques of single-variable calculus,    2
The overall goal of the course it to provide the participants with a sound under    2
The MATH 2043 and 3043 is a rigorous sequence in analysis on the line and higher    2
Basic elements of starting a new business in information technology; exploiting     2
The topics discussed in this course include survival models, life tables and sel    2
This course is a general introduction to the changing responsibilities of busine    2
For SB&M students, and programs that designate the course as a required/specifie    2
Name: count, dtype: Int64

In [34]:
# sjednocení placeholder hodnot ve sloupci aims
AIMS_PLACEHOLDERS = [
    "The aims of the course has not been saved in this language version.",
    "-- item not defined --"
]

vse_df["aims"] = (
    vse_df["aims"]
    .replace(AIMS_PLACEHOLDERS, pd.NA)
)

# kontrola výsledku
print("VŠE")

print(
    vse_df["aims"]
    .isna()
    .sum()
)

print("\nPartneři")

print(
    partner_df["aims"]
    .isna()
    .sum()
)

VŠE
30

Partneři
2

In [35]:
# kontrola hodnoty "Individual Course of Study"
partner_df[
    partner_df["aims"]
    .str.contains(
        "Individual Course of Study",
        na=False
    )
][
    [
        "university",
        "course_code",
        "course_title",
        "aims",
        "source_url"
    ]
]

,university,course_code,course_title,aims,source_url
248,University of Canterbury,MATH393,Individual Course of Study,Individual Course of Study,https://courseinfo.canterbury.ac.nz/GetCourseDetails.aspx?course=MATH393&occurrence=26S1(C)&year=2026
249,University of Canterbury,MATH394,Individual Course of Study,Individual Course of Study,https://courseinfo.canterbury.ac.nz/GetCourseDetails.aspx?course=MATH394&occurrence=26S2(C)&year=2026
317,University of Canterbury,STAT394,Individual Course of Study,Individual Course of Study,https://courseinfo.canterbury.ac.nz/GetCourseDetails.aspx?course=STAT394&occurrence=26S2(C)&year=2026

In [36]:
# kontrola záznamů s hodnotou "Individual Course of Study"
individual_courses = partner_df[
    partner_df["aims"].eq("Individual Course of Study")
].copy()

individual_courses[
    [
        "university",
        "course_code",
        "course_title",
        "credits",
        "ects_credits",
        "aims",
        "course_content",
        "learning_outcomes",
        "assessment_methods",
        "literature",
        "source_url"
    ]
]

,university,course_code,course_title,credits,ects_credits,aims,course_content,learning_outcomes,assessment_methods,literature,source_url
248,University of Canterbury,MATH393,Individual Course of Study,15.0,7.5,Individual Course of Study,<NA>,<NA>,<NA>,<NA>,https://courseinfo.canterbury.ac.nz/GetCourseDetails.aspx?course=MATH393&occurrence=26S1(C)&year=2026
249,University of Canterbury,MATH394,Individual Course of Study,15.0,7.5,Individual Course of Study,<NA>,<NA>,<NA>,<NA>,https://courseinfo.canterbury.ac.nz/GetCourseDetails.aspx?course=MATH394&occurrence=26S2(C)&year=2026
317,University of Canterbury,STAT394,Individual Course of Study,15.0,7.5,Individual Course of Study,<NA>,<NA>,<NA>,<NA>,https://courseinfo.canterbury.ac.nz/GetCourseDetails.aspx?course=STAT394&occurrence=26S2(C)&year=2026

In [37]:
# odstranění neanalyzovatelných záznamů typu Individual Course of Study
partner_df = partner_df[
    ~partner_df["course_code"].isin([
        "MATH393",
        "MATH394",
        "STAT394"
    ])
].reset_index(drop=True)

# kontrola odstranění
partner_df[
    partner_df["course_code"].isin([
        "MATH393",
        "MATH394",
        "STAT394"
    ])
]

Empty DataFrame
Columns: [course_title, course_code, university, country, source_url, academic_year, semester, semester_normalized, study_level, credits, credit_system, ects_credits, aims, course_content, learning_outcomes, assessment_methods, literature]
Index: []

In [38]:
# kontrola aims po čištění
print("VŠE")

print(
    vse_df["aims"]
    .isna()
    .sum()
)

print("\nPartneři")

print(
    partner_df["aims"]
    .isna()
    .sum()
)

print("\nNejčastější začátky aims u partnerů:")

display(
    partner_df["aims"]
    .dropna()
    .str[:80]
    .value_counts()
    .head(10)
)

VŠE
30

Partneři
2

Nejčastější začátky aims u partnerů:

aims
This special topic will allow flexibility to offer new or one-off courses of str    4
This is a project-based course that provides students an opportunity to integrat    4
Analysis of sequentially collected data including data modelling and forecasting    3
This course analyses the nature and problem of risk and uncertainty and consumer    2
This calculus-based course is intended to develop a rigorous understanding of co    2
The course covers basic applications and techniques of single-variable calculus,    2
An introduction to the ideas, techniques and applications of statistics and prob    2
An internship or consultancy project is an opportunity to experience a professio    2
The overall goal of the course it to provide the participants with a sound under    2
This course is a supervised course which trains student to do proper economic re    2
Name: count, dtype: Int64

Ve sloupci `aims` byly u datasetu VŠE identifikovány systémové placeholder hodnoty `The aims of the course has not been saved in this language version.` a `-- item not defined --`, které neobsahovaly skutečný obsah sylabu. Tyto hodnoty byly převedeny na chybějící hodnoty. Současně byly z partnerského datasetu odstraněny tři záznamy typu `Individual Course of Study`, které po odstranění placeholder hodnot neobsahovaly žádné relevantní obsahové informace pro porovnání sylabů.

## Kontrola sloupce `course_content`

In [39]:
# kontrola hodnot course_content
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["course_content"].isna().sum())

print("Prázdné řetězce:",
      (vse_df["course_content"].str.strip() == "").sum())

print("\nDélka textu:")

print(
    vse_df["course_content"]
    .str.len()
    .describe()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["course_content"].isna().sum())

print("Prázdné řetězce:",
      (partner_df["course_content"].str.strip() == "").sum())

print("\nDélka textu:")

print(
    partner_df["course_content"]
    .str.len()
    .describe()
)

VŠE
Chybějící hodnoty: 0
Prázdné řetězce: 0

Délka textu:
count         133.0
mean     974.819549
std      912.169474
min            22.0
25%           254.0
50%           722.0
75%          1433.0
max          4410.0
Name: course_content, dtype: Float64

Partneři
Chybějící hodnoty: 643
Prázdné řetězce: 0

Délka textu:
count          256.0
mean     1050.789062
std       994.219818
min              1.0
25%           370.75
50%            682.0
75%          1325.25
max           6949.0
Name: course_content, dtype: Float64

In [40]:
# podíl chybějících hodnot course_content podle univerzit
missing_course_content_ratio = (
    partner_df
    .groupby("university")["course_content"]
    .apply(lambda x: x.isna().mean())
    .reset_index(name="missing_ratio")
)

missing_course_content_ratio["missing_ratio"] = (
    missing_course_content_ratio["missing_ratio"] * 100
).round(1)

missing_course_content_ratio.sort_values(
    "missing_ratio",
    ascending=False
)

                                           university  missing_ratio
2                                  Queen's University          100.0
3  The Hong Kong University of Science and Technology          100.0
4                            University of Canterbury          100.0
0                        BI Norwegian Business School            0.8
1            Instituto Tecnológico Autónomo de México            0.0
5                             University of Edinburgh            0.0

In [41]:
# nejčastější začátky textů ve sloupci course_content
print("VŠE")

display(
    vse_df["course_content"]
    .dropna()
    .str[:80]
    .value_counts()
    .head(15)
)

print("\nPartneři")

display(
    partner_df["course_content"]
    .dropna()
    .str[:80]
    .value_counts()
    .head(15)
)

VŠE

course_content
The content of the course has not been saved in this language version.              27
-- item not defined --                                                               4
1.Concept of Law, Sources of International, EU and National Law, Legal Systems (     2
1) Introduction to the financial economics, money and financial markets (basic t     2
1. Managerial accounting. Costing of costs and price. Budgeting. 2. Short-term f     1
1.Marketing and commercial communication (allowance 2/0) a. Marketing communicat     1
1.Data analysis (allowance 0/12) a. Office programmes for data analysis. b. Intr     1
1.Project management (allowance 0/14) a. Fundamentals of project management theo     1
1.Basic database notions. (allowance 0/0) 2.Introduction of the Microsoft Office     1
1.The Basics of Office 365 (allowance 0/4) a. Introduction to the subject. b. Of     1
1.Marketing and strategic marketing planning (allowance 4/0) a. Marketing, marke     1
1.Globalization of the world economy, basic characteristics and main trends of e     1
1.Channels of distribution, definitions, types, factors of selection. Processing     1
1.Business plan (allowance 6/0) a. purpose b. users c. structure 2.The processin     1
1. An essence of financial management, corporate objectives, rational and irrati     1
Name: count, dtype: Int64

Partneři

course_content
This calculus-based course is intended to develop a rigorous understanding of co    2
This course is intended to develop a rigorous understanding of core economic mod    2
-                                                                                   2
Examination of strategic financial and non-financial objectives across organizat    1
The course will be divided in a theoretical and a more empirical, or historical,    1
The course consists of three subtopics: Subtopic 1: Financial Accounting Main fi    1
Economics. In order to clarify what lies in the overall goal of acquiring broad     1
Python basics Programming environment. Variables and data types. Input and outpu    1
The course covers the following topics: Loading, cleaning, and exploration of da    1
Introduction to Spreadsheet Modeling. Introduction to Optimization and Linear Pr    1
In-house data External relevant data Extraction of data Decision analysis Manage    1
Introduction, installation of Python, Jupyter lab, IDEs. Executing Python code.     1
Plenary sessions consisting of lectures and interactive workshops in small group    1
Problem-solving; methods and processes Problem-solving techniques Teamwork in pr    1
Introduction to information systems (IS) and information technology (IT) Element    1
Name: count, dtype: Int64

In [42]:
# kontrola hodnoty "-"
partner_df[
    partner_df["course_content"] == "-"
][
    [
        "university",
        "course_code",
        "course_title",
        "course_content",
        "learning_outcomes",
        "assessment_methods",
        "literature",
        "source_url"
    ]
]

,university,course_code,course_title,course_content,learning_outcomes,assessment_methods,literature,source_url
94,BI Norwegian Business School,TEM 0420,Strategic Risk Analysis,-,"After finishing this course, the student should have knowledge about: Differing types of risk that organizations fac...",Ordinary examination,<NA>,https://portal.bi.no/kurs/#/course/en/TEM/0420/202620
97,BI Norwegian Business School,TEM 0240,Social Tensions and Connections in a Polarized World,-,"After completion of this course, students should have knowledge of: How identity drives information selection and in...",Ordinary examination,<NA>,https://portal.bi.no/kurs/#/course/en/TEM/0240/202620

In [43]:
# placeholder hodnoty ve sloupci course_content
COURSE_CONTENT_PLACEHOLDERS = [
    "The content of the course has not been saved in this language version.",
    "-- item not defined --",
    "-"
]

vse_df["course_content"] = (
    vse_df["course_content"]
    .replace(COURSE_CONTENT_PLACEHOLDERS, pd.NA)
)

partner_df["course_content"] = (
    partner_df["course_content"]
    .replace(COURSE_CONTENT_PLACEHOLDERS, pd.NA)
)

# kontrola výsledku
print("VŠE")

print(
    vse_df["course_content"]
    .isna()
    .sum()
)

print("\nPartneři")

print(
    partner_df["course_content"]
    .isna()
    .sum()
)

VŠE
31

Partneři
645

Ve sloupci `course_content` byly identifikovány systémové placeholder hodnoty `The content of the course has not been saved in this language version.`, `-- item not defined --` a `-`, které neobsahovaly skutečný obsah sylabu. Tyto hodnoty byly převedeny na chybějící hodnoty.

## Kontrola sloupce `learning_outcomes`

In [44]:
# kontrola hodnot learning_outcomes
print("VŠE")
print("Chybějící hodnoty:",
      vse_df["learning_outcomes"].isna().sum())

print("Prázdné řetězce:",
      (vse_df["learning_outcomes"].str.strip() == "").sum())

print("\nDélka textu:")

print(
    vse_df["learning_outcomes"]
    .str.len()
    .describe()
)

print("\nPartneři")
print("Chybějící hodnoty:",
      partner_df["learning_outcomes"].isna().sum())

print("Prázdné řetězce:",
      (partner_df["learning_outcomes"].str.strip() == "").sum())

print("\nDélka textu:")

print(
    partner_df["learning_outcomes"]
    .str.len()
    .describe()
)

VŠE
Chybějící hodnoty: 0
Prázdné řetězce: 0

Délka textu:
count         133.0
mean      498.81203
std      419.585314
min            22.0
25%           195.0
50%           459.0
75%           651.0
max          3125.0
Name: learning_outcomes, dtype: Float64

Partneři
Chybějící hodnoty: 165
Prázdné řetězce: 0

Délka textu:
count         734.0
mean     722.730245
std      485.374072
min            85.0
25%          412.25
50%           591.0
75%           893.0
max          3951.0
Name: learning_outcomes, dtype: Float64

In [45]:
# podíl chybějících hodnot learning_outcomes podle univerzit
missing_learning_outcomes_ratio = (
    partner_df
    .groupby("university")["learning_outcomes"]
    .apply(lambda x: x.isna().mean())
    .reset_index(name="missing_ratio")
)

missing_learning_outcomes_ratio["missing_ratio"] = (
    missing_learning_outcomes_ratio["missing_ratio"] * 100
).round(1)

missing_learning_outcomes_ratio.sort_values(
    "missing_ratio",
    ascending=False
)

                                           university  missing_ratio
2                                  Queen's University          100.0
4                            University of Canterbury           43.4
1            Instituto Tecnológico Autónomo de México           33.3
3  The Hong Kong University of Science and Technology            0.3
0                        BI Norwegian Business School            0.0
5                             University of Edinburgh            0.0

In [46]:
# nejčastější začátky textů ve sloupci learning_outcomes
print("VŠE")

display(
    vse_df["learning_outcomes"]
    .dropna()
    .str[:80]
    .value_counts()
    .head(15)
)

print("\nPartneři")

display(
    partner_df["learning_outcomes"]
    .dropna()
    .str[:80]
    .value_counts()
    .head(15)
)

VŠE

learning_outcomes
The learning outcomes of the course has not been saved in this language version.    27
Upon successful completion of this course, students will be able to: - understan    12
-- item not defined --                                                               3
Upon successful completion of this course, students will be able to: - describe      3
Upon successful completion of this course, students will be able to: - explain t     3
Upon successful completion of the course, students will be able to: - understand     2
Upon successful completion of this course, students will be able to - analyze th     2
Upon successful completion of this course, students will be able to understand a     2
Upon successful completion of the course, students will be able to solve the fol     2
Upon successful completion of this course, students will be able to -define basi     1
Upon successful completion of this course, students will be able to: -understand     1
Upon successful completion of this course, students will be able to - use advanc     1
Upon successful completion of this course, students will be able to - plan, cont     1
Upon successful completion of this course, students will be able to work with th     1
Upon successful completion of this course, students will be able to - share info     1
Name: count, dtype: Int64

Partneři

learning_outcomes
On completion of this course, the student will be able to: A knowledge and under    18
On completion of this course, the student will be able to: Understand and discus    12
On completion of this course, the student will be able to: Understand and critic     9
1. Recognize and use appropriately important technical terms and definitions. 2.     6
On completion of this course, the student will be able to: Have had the opportun     5
On completion of this course, the student will be able to: Demonstrate a knowled     4
1. Equip with broad and useful knowledge to various topics which are not covered     4
The objectives of the course are (related to the specific BCom Learning Outcomes     3
1. Understand the logic, scientific basis, and critical thinking of economic ana     3
1. Define basic programming elements such as variables, control, loops and funct     2
On completion of this course, the student will be able to: Reflect upon and crit     2
1. Analyze firm financial performance through basic financial statement analysis     2
On completion of this course, the student will be able to: Understand, criticall     2
1. Describe fundamental concepts and techniques for determining the asymptotic b     2
1. Develop original solutions to computer science engineering problems of signif     2
Name: count, dtype: Int64

In [48]:
# odstranění placeholderů a konzervativních boilerplate prefixů z learning_outcomes

LEARNING_OUTCOMES_PLACEHOLDERS = [
    "The learning outcomes of the course has not been saved in this language version.",
    "-- item not defined --"
]

LEARNING_OUTCOMES_PATTERNS = [

    # obecné úvodní boilerplate formulace
    r"^Upon successful completion of this course, students will be able to:?\s*",
    r"^Upon successful completion of this course, student will be able to:?\s*",
    r"^Upon successful completion of the course, students will be able to:?\s*",
    r"^Upon successful completion of the course, student will be able to:?\s*",

    r"^Upon successful completion of this course, students will:?\s*",
    r"^Upon successful completion of this course, student will:?\s*",

    r"^Upon successful completion, students will be able to:?\s*",
    r"^Upon successful completion, student will be able to:?\s*",

    r"^Upon successful completion students will:?\s*",
    r"^Upon successful completion student will:?\s*",

    r"^Upon successful completion of this course,?\s*",
    r"^Upon successful completion of the course,?\s*",

    # completion / after completion
    r"^Upon completion of the course, students:?\s*",
    r"^Upon completion of the course, student:?\s*",

    r"^Upon completion of this course, students:?\s*",
    r"^Upon completion of this course, student:?\s*",

    r"^Upon completion of the course, students will:?\s*",
    r"^Upon completion of the course, student will:?\s*",

    r"^Upon completion of this course, students will:?\s*",
    r"^Upon completion of this course, student will:?\s*",

    r"^Upon the completion of the course, the students should:?\s*",
    r"^Upon the completion of the course, the student should:?\s*",

    r"^Upon the successful completion of the course,?\s*",

    r"^After successful completion of this course,?\s*",
    r"^After successful passing the course,?\s*",

    r"^After completing the course, the student:?\s*",
    r"^After completing the course, students will:?\s*",

    r"^After taking the course, the students shall be able to:?\s*",

    # by the end / on completion
    r"^By the end of the course,? the students will:?\s*",
    r"^By the end of the course,? the student will:?\s*",

    r"^By the end of this course,? the student should be able to:?\s*",

    r"^By the end of this course it is expected that the student will be able to:?\s*",

    r"^By the end of the [A-Z]{2,}\s*\d{3}\s*course it is expected that students will be able to:?\s*",

    r"^By the end of the course the candidate:?\s*",

    r"^On completion of this course, the student will be able to:?\s*",

    # objectives
    r"^The objectives of the course are \(related to the specific BCom Learning Outcomes in brackets\):?\s*",

    r"^The objectives of the course are \(related to the specific BCom Learning Outcomes\):?\s*",

    r"^The objectives of the course are:?\s*",

    r"^The broad objectives of the course are that students will demonstrate an understanding of:?\s*",

    r"^The outcomes of the course are:?\s*"
]

# administrativní instrukce k vyplnění sylabu
LEARNING_OUTCOMES_ADMIN_PATTERNS = [
    r"^All learning outcomes should be structured as bullet points:?\s*https?://\S+\s*",

    r"^The bullet points in all the learning outcome categories need an introduction\.\s*See more about structuring and wording of learning outcomes,?\s*see NOKUT:?\s*NOKUT:?\s*https?://\S+\s*",

    r"^Learning objectives should be struktured as points\.\s*Information about this here:?\s*https?://\S+\s*",

    r"^Læringsutbytte skal struktureres med kulepunkter ref\.?\s*NOKUT\s*https?://\S+\s*"
]


def clean_learning_outcomes(text):

    if pd.isna(text):
        return pd.NA

    text = str(text)

    # sjednocení whitespace
    text = re.sub(r"\s+", " ", text).strip()

    # placeholdery
    if text in LEARNING_OUTCOMES_PLACEHOLDERS:
        return pd.NA

    # odstranění administrativních instrukcí
    for pattern in LEARNING_OUTCOMES_ADMIN_PATTERNS:
        text = re.sub(pattern, "", text, flags=re.IGNORECASE).strip()

    # odstranění boilerplate prefixů
    for pattern in LEARNING_OUTCOMES_PATTERNS:
        text = re.sub(pattern, "", text, flags=re.IGNORECASE).strip()

    if text == "":
        return pd.NA

    return text


# aplikace cleaningu

vse_df["learning_outcomes"] = (
    vse_df["learning_outcomes"]
    .apply(clean_learning_outcomes)
)

partner_df["learning_outcomes"] = (
    partner_df["learning_outcomes"]
    .apply(clean_learning_outcomes)
)

In [50]:
# kontrola po cleaningu learning_outcomes

print("VŠE")
print("Chybějící hodnoty:", vse_df["learning_outcomes"].isna().sum())
print("Prázdné řetězce:", (vse_df["learning_outcomes"].fillna("").str.strip() == "").sum())

display(
    vse_df["learning_outcomes"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(30)
)

print("\nPartneři")
print("Chybějící hodnoty:", partner_df["learning_outcomes"].isna().sum())
print("Prázdné řetězce:", (partner_df["learning_outcomes"].fillna("").str.strip() == "").sum())

display(
    partner_df["learning_outcomes"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(40)
)

VŠE
Chybějící hodnoty: 31
Prázdné řetězce: 31

learning_outcomes
- understand the content of financial statements for external users; - define and explain the nature of fundamental elements of financial statements;     3
- explain the differences in substance and management accounting system design for product costing and compare it with the accounting information for     2
- analyze theoretically economic issues - describe the relationship between economic theory and economic reality - apply basic principles of human eco    2
- explain reasons of chosen environmental problems of different environmental fields; - shortly characterize approaches of leading schools of economic    1
- work with patterns and context in real functioning socioeconomic system, including inter- action relations among nature, society and economic proces    1
- identify a problem; - propose a hypothesis; - find and critically assess available information (including academic resources in English); - formulat    1
- recognize and describe various market structures and firm strategies - measure market power and apply basic concepts of economic analysis of market     1
- demonstrate knowledge and understanding of the most important aspects of consumer theory and theory of the firm - describe the behavior of economic     1
- calculate derivatives of functions of one variable composed of elementary functions, use it to calculate the tangent to a function at a point, - cal    1
- describe functioning of economic system in its complexity - explain problems of economic growth - discuss the possibilities and limits of individual    1
students would be able to: - evaluate the impacts of overseas expansion on the world economy; - compare the process of industrial revolution in Great     1
- describe the most important events of economic and political history of Europe after the Great War (until the break-up of the USSR); - analyze cause    1
students will be able to - evaluate the importance of the Czech Republic’s membership in the European Union; - describe the mechanism of the EU functi    1
able to - explain the main principles of modern economic theory in the area of the public sector - distinguish between market and non-market process o    1
Student will -Understand the concepts of DevSecOps, Data Science and Machine Learning and how they are integrated in MLOps. - Understand the challenge    1
- apply economic theory to the labour market - build a model of behaviour and decision-making of various players on the labour market and the impact o    1
the students should - understand the rational forces that shape people’s decisions in various aspects of their lives - be familiar with the basic econ    1
the students: - will be able to orient themselves in economic texts (both popular and professional) and to interpret and assess them correctly; - will    1
- apply their theoretical knowledge on real-life problems related to both banks and nonbank financial institutions; - explain the main features of fin    1
build a simple economic model, find appropriate data and use standard econometric tools to find an answer to research question.                           1
understand and discuss: - Necessities of management of data and analytics alignment with goals of an organization and how to achieve it - Approaches t    1
- Learn how to create and support a strong story with arguments and information. - Be able to create a powerful presentation. - Gain excellent present    1
- Apply knowledge and skills gained in the course of study in performing work tasks - Assess the functioning of the company's or institution's analyti    1
be able to: - Understand and apply advanced machine learning techniques. - Connect a practical assignment with the information contained in the data a    1
the students will be provided with the theoretical tools and practical experience necessary to carry out applied econometric research.                    1
- identify the scope of economic research - define and explain basic economic categories and causalities - characterize behavior of both consumer as w    1
- develop and apply basic pieces of theoretical knowledge regarding the national economy; - summarize elementary goals of economic and social policy;     1
Students will be able to - explain the role of law in society - enumerate different types of legal norm - describe the law making process - interpret     1
- enumerate the main terms and concepts used in the core macroeconomic courses and to explain their meaning, - demonstrate the range of issues and top    1
- understand the system of public finance in the Czech Republic; - work with key data sources on public finances, which are available on the internet     1
Name: count, dtype: int64

Partneři
Chybějící hodnoty: 165
Prázdné řetězce: 165

learning_outcomes
1. Equip with broad and useful knowledge to various topics which are not covered by existing courses. 2. (Each offering under the umbrella will have s    3
1. Describe fundamental concepts and techniques for determining the asymptotic behavior of real-valued functions defined in natural numbers. 2. Explai    2
1. Identify and discuss forces that shape business activities and vice-versa. In particular, the environment and consumerism. 2. Identify and discuss     2
1. Utilize context-free grammars to identify and define the formal syntax of programming languages. 2. Apply general tools such as Bison and Flex to c    2
1. Apply appropriate modeling techniques to design software for an application of medium complexity: model and document data and processing requiremen    2
1. Develop original solutions to computer science engineering problems of significant complexity. 2. Utilize prior knowledge, independent research, pu    2
1. Demonstrate an in-depth and substantial knowledge and understanding on the topic chosen for the independent study. 2. Apply suitable business theor    2
1. Model and solve simple problems using first order odes. 2. Solve linear, constant coefficient second-order odes. 3. Use the Laplace transform metho    2
1. Understand the models used to model decrements used in insurances, annuities, and investments and how to calculate probabilities based on those mod    2
1. Write a proposal for a company project. 2. Suggest a scope for a company research problem. 3. Identify suitable risk management and business intell    2
1. Recognize and use appropriately important technical terms and definitions. 2. Use calculus and linear algebra to formulate and apply the fundamenta    2
1. Use Python data structures and flow control constructs and their applications [WA1] 2. Apply the Python language to design, implement and test prog    2
1. Search, brainstorm and formulate research ideas. 2. Integrate and apply knowledge learnt to real life phenomena. 3. Apply research findings to expl    2
1. Explain advanced mathematical theories, concepts and principles using precise mathematical language. 2. Apply independent judgment to investigative    2
1. Identify the basic principles and practices involved in either starting a company or planning to work in a start-up company, and any pitfalls to be    2
1. Analyze firm financial performance through basic financial statement analysis. 2. Apply the concept of time value of money to make correct financia    2
A knowledge and understanding of economic analysis including principles, models and associated mathematical and statistical techniques, along with app    2
1. Demonstrate the skill to use Excel spreadsheet, particularly around the following aspects: working with Excel; creating formulas; manipulating info    1
1. Understand and apply basic statistical analysis to practical problems and to present the result in a meaningful way. 2. Interpret the results of bu    1
1. Understand fundamental programming concepts in Python. 2. Apply Python syntax and control structures to solve business problems (Apply level). 3. B    1
1. Identify different types of probability distributions and explain their appropriate applications. 2. Understand the importance of probability theor    1
1. Identify and analyze some of the most important problems in supply chain management in different industries. 2. Create supply chain solutions that     1
1. Identify and analyze some of the most important problems in quality management in different industries. 2. Create quality management solutions that    1
1. Illustrate the basic logistics management concepts and the role of logistics management in firms. 2. Explain the key logistics processes and operat    1
1. Configure EIGRP Routing Protocol. Design and implement an optimized EIGRP routing configuration for a given network topology. 2. Configure and trou    1
1. Understand the philosophy, theory, and practice of supply chain management. 2. Understand the design, configuration and planning of supply chains.     1
1. Develop more confidence and appreciation of the quantitative reasoning skill to approach business problems, evaluate solutions, and make actionable    1
1. Analyze critical dilemmas presented by digital platforms and their impact on established business assumptions. 2. Explain core concepts, theories,     1
1. Evaluate entrepreneurial opportunities using technology-driven frameworks. 2. Analyze startup business models to assess growth potential. 3. Apply     1
1. Approach real-world Natural Language Processing problems using Deep Learning methods. 2. Be familiar with various concepts and theoretical framewor    1
1. Develop proficiency in R programming. 2. Understand data structures and manipulation. 3. Import various data formats into R using RStudio. 4. Provi    1
1. Identify artificial intelligence trends and developments. 2. Classify common AI models and understand their characteristics. 3. Analyze the potenti    1
1. Understand the core concept and characteristics of Big Data. 2. Understand the key components of the Hadoop framework and the use of the Hadoop Dis    1
1. Compare and contrast the role of each layer in two recognized network models: The TCP/IP model and the OSI model. Analyse and evaluate the roles of    1
1. Acquire general programming knowledge with Python. 2. Model business data with Python data type. 3. Process business data with Python supported ope    1
1. Analyze social and business issues for protecting innovations in a legal and strategic context, including international policy and trade issues 2.     1
1. Describe the new roles of competitive and macro environment forces as Internet and AI becomes more ubiquitous 2. Analyze the strategic uses and dev    1
1. Recall and state fundamentals of information infrastructure from technology, social, business and policy perspectives 2. Explain and interpret info    1
1. Understand and master basic theoretical concepts and methods in statistical thinking and reasoning, and be able to decide what statistical techniqu    1
1. Gain an understanding of how managers use business analytics to formulate and solve business problems and to support managerial decision making. 2.    1
Name: count, dtype: int64

Ve sloupci `learning_outcomes` byly identifikovány systémové placeholder hodnoty `The learning outcomes of the course has not been saved in this language version.` a `-- item not defined --`, které neobsahovaly skutečný obsah sylabu. Tyto hodnoty byly převedeny na chybějící hodnoty. Současně byly odstraněny opakující se úvodní boilerplate formulace a administrativní instrukce k vyplňování výsledků učení, které nepředstavovaly obsahové informace o předmětu. Obecné formulace tvořící součást konkrétních výsledků učení byly ponechány beze změny.

## Kontrola sloupce `assessment_methods`

In [52]:
# kontrola sloupce assessment_methods

print("VŠE")
print("Chybějící hodnoty:", vse_df["assessment_methods"].isna().sum())
print("Prázdné řetězce:", (vse_df["assessment_methods"].fillna("").str.strip() == "").sum())

display(
    vse_df["assessment_methods"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(30)
)

print("\nPartneři")
print("Chybějící hodnoty:", partner_df["assessment_methods"].isna().sum())
print("Prázdné řetězce:", (partner_df["assessment_methods"].fillna("").str.strip() == "").sum())

display(
    partner_df["assessment_methods"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(40)
)

VŠE
Chybějící hodnoty: 0
Prázdné řetězce: 0

assessment_methods
Mid-term test(s): 40% Final test: 60%                                                                                                                     8
Mid-term test(s): 50% Final test: 50%                                                                                                                     5
Term paper: 40% Final test: 60%                                                                                                                           3
Active lecture/seminar/workshop/tutorial participation20 %: 20% Mid-term test(s)20 %: 20% Final test60 %: 60% Total100 %: 100%                            3
Active lecture/seminar/workshop/tutorial participation30 %: 0% Final test70 %: 100% Total100 %: 100%                                                      3
Active lecture/seminar/workshop/tutorial participation: 20% Final test: 80%                                                                               3
Active lecture/seminar/workshop/tutorial participation: 30% Mid-term test(s): 30% Final test: 40%                                                         3
Mid-term test(s): 30% Final test: 70%                                                                                                                     3
Term paper: 30% Mid-term test(s): 40% Final oral exam: 30%                                                                                                2
Active lecture/seminar/workshop/tutorial participation10 %: 10% Mid-term test(s)30 %: 30% Final test60 %: 60% Total100 %: 100%                            2
Mid-term test(s)40 %: 40% Final test60 %: 60% Total100 %: 100%                                                                                            2
Active lecture/seminar/workshop/tutorial participation: 20% Mid-term test(s): 30% Final test: 50%                                                         2
Final test: 100%                                                                                                                                          2
Active lecture/seminar/workshop/tutorial participation: 10% Mid-term test(s): 30% Final test: 60%                                                         2
Mid-term test(s): 20% Final test: 80%                                                                                                                     2
Active lecture/seminar/workshop/tutorial participation: 6% Term paper: 18% Mid-term test(s): 38% Final test: 26% Home works: 12%                          2
Term paper: 50% Final test: 50%                                                                                                                           1
Active lecture/seminar/workshop/tutorial participation: 20% Term paper: 70% Presentation or defence: 10%                                                  1
Term paper: 30% Final test: 70%                                                                                                                           1
Active lecture/seminar/workshop/tutorial participation: 20% Presentation or defence: 30% Final test: 40% Evaluation of another team's presentation: 10    1
Active lecture/seminar/workshop/tutorial participation: 12% Final oral exam: 88%                                                                          1
Active lecture/seminar/workshop/tutorial participation: 6% Term paper: 30% Final test: 64%                                                                1
Active lecture/seminar/workshop/tutorial participation: 6% Final test: 40% Final oral exam: 54%                                                           1
Active lecture/seminar/workshop/tutorial participation: 78% Term paper: 22%                                                                               1
Active lecture/seminar/workshop/tutorial participation: 26% Term paper: 34% Final test: 40%                                                               1
Active lecture/seminar/workshop/tutorial participation10 %: 10% Term paper30 %: 30% Mid-term test(s)20 %: 0% Final test20 %: 30% Final oral exam20 %:     1
Active lecture/seminar/workshop/tutorial participation: 6% Term paper: 20% Final test: 74%                                                                1
Active lecture/seminar/workshop/tutorial participation50 %: 50% Final test50 %: 50% Total100 %: 100%                                                      1
Presentation or defence15 %: 15% Mid-term test(s)30 %: 30% Final test40 %: 40% Homeworks15 %: 15% Total100 %: 100%                                        1
Active lecture/seminar/workshop/tutorial participation10 %: 10% Term paper20 %: 20% Presentation or defence10 %: 10% Mid-term test(s)30 %: 30% Final t    1
Name: count, dtype: Int64

Partneři
Chybějící hodnoty: 555
Prázdné řetězce: 555

assessment_methods
Written Exam 0 %, Coursework 100 %, Practical Exam 0 %                                                                                                    35
Ordinary examination                                                                                                                                      30
Written Exam 70 %, Coursework 30 %, Practical Exam 0 %                                                                                                    13
Exam category: School Exam Form of assessment: Written School Exam - pen and paper Exam/hand-in semester: First Semester Weight: 100 Grouping: Individ    11
Exam category: School Exam Form of assessment: Written School Exam - digital Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Su    11
Written Exam 80 %, Coursework 20 %, Practical Exam 0 %                                                                                                     9
Written Exam 60 %, Coursework 40 %, Practical Exam 0 %                                                                                                     9
Written Exam 75 %, Coursework 25 %, Practical Exam 0 %                                                                                                     7
Exam category: School Exam Form of assessment: Structured Test Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Support material     7
Written Exam 50 %, Coursework 50 %, Practical Exam 0 %                                                                                                     5
Written Exam 90 %, Coursework 10 %, Practical Exam 0 %                                                                                                     3
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Group/Individual (1 - 3) Dura     3
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 40 Grouping: Group/Individual (1 - 3) Durat     2
Midterm test (40%) Essay (20%) Final exam (40%)                                                                                                            2
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 30 Grouping: Group/Individual (1 - 3) Durat     2
Exam category: Submission Form of assessment: Submission other than PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Group/Individual (     2
Exam category: Submission Form of assessment: Submission other than PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Group (4 - 6) Dura     2
Written Exam 65 %, Coursework 35 %, Practical Exam 0 %                                                                                                     2
Proposal (15%) Final Presentation (20%) Project Deliverables (25%) Report (40%)                                                                            2
Volunteering Experience and Reflection (30%) Circular Economy Analysis (30%) Final Exam (40%)                                                              2
Written Exam 0 %, Coursework 70 %, Practical Exam 30 %                                                                                                     2
Written Exam 85 %, Coursework 15 %, Practical Exam 0 %                                                                                                     2
Written Exam 100 %, Coursework 0 %, Practical Exam 0 %                                                                                                     2
Exam category: School Exam Form of assessment: Written School Exam - pen and paper Exam/hand-in semester: First Semester Weight: 30 Grouping: Individu     2
Exam category: Submission Form of assessment: Portfolio Assessment PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Duration     2
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 30 Grouping: Group/Individual (1 - 4) Durat     2
Exam category: Submission Form of assessment: Submission other than PDF Exam/hand-in semester: First Semester Weight: 60 Grouping: Group (2 - 6) Durat     1
Exam category: Submission Form of assessment: Submission other than PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Duratio     1
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 35 Grouping: Individual Duration: 1 Semeste     1
Exam category: Submission Form of assessment: Portfolio Assessment PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Group/Individual (1     1
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Duration: 4 Hour(s     1
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 70 Grouping: Individual Duration: 5 Week(s)     1
Exam category: Submission Form of assessment: Submission other than PDF Exam/hand-in semester: First Semester Weight: 30 Grouping: Group (1 - 3) Durat     1
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 70 Grouping: Group (3 - 5) Duration: 1 Seme     1
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Group/Individual (1 - 4) Dura     1
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 65 Grouping: Group (1 - 3) Duration: 2 Mont     1
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 40 Grouping: Group/Individual (1 - 2) Durat     1
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 40 Grouping: Group (1 - 3) Duration: 1 Week     1
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Duration: 8 Hour(s     1
Exam category: Activity, Oral Form of assessment: Oral Exam Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Duration: 30 Minute     1
Name: count, dtype: Int64

In [55]:
# technické čištění assessment_methods

ASSESSMENT_METHODS_PLACEHOLDERS = [
    "-- item not defined --"
]


def clean_assessment_methods(text):

    if pd.isna(text):
        return pd.NA

    text = str(text)

    # doplnění mezery mezi textem a číslem
    text = re.sub(r"([a-zA-Z])(\d)", r"\1 \2", text)

    # doplnění mezery mezi závorkou a číslem
    text = re.sub(r"(\))(\d)", r"\1 \2", text)

    # sjednocení zápisu procent
    text = re.sub(r"(\d)\s*%", r"\1 %", text)

    # sjednocení whitespace
    text = re.sub(r"\s+", " ", text).strip()

    # placeholdery
    if text in ASSESSMENT_METHODS_PLACEHOLDERS:
        return pd.NA

    # prázdné hodnoty
    if text == "":
        return pd.NA

    return text


# aplikace cleaningu

vse_df["assessment_methods"] = (
    vse_df["assessment_methods"]
    .apply(clean_assessment_methods)
)

partner_df["assessment_methods"] = (
    partner_df["assessment_methods"]
    .apply(clean_assessment_methods)
)

In [56]:
# kontrola po cleaningu assessment_methods

print("VŠE")
print("Chybějící hodnoty:", vse_df["assessment_methods"].isna().sum())
print("Prázdné řetězce:", (vse_df["assessment_methods"].fillna("").str.strip() == "").sum())

display(
    vse_df["assessment_methods"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(30)
)

print("\nPartneři")
print("Chybějící hodnoty:", partner_df["assessment_methods"].isna().sum())
print("Prázdné řetězce:", (partner_df["assessment_methods"].fillna("").str.strip() == "").sum())

display(
    partner_df["assessment_methods"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(40)
)

VŠE
Chybějící hodnoty: 0
Prázdné řetězce: 0

assessment_methods
Mid-term test(s): 40 % Final test: 60 %                                                                                                   8
Mid-term test(s): 50 % Final test: 50 %                                                                                                   5
Term paper: 40 % Final test: 60 %                                                                                                         3
Active lecture/seminar/workshop/tutorial participation 20 %: 20 % Mid-term test(s) 20 %: 20 % Final test 60 %: 60 % Total 100 %: 100 %    3
Active lecture/seminar/workshop/tutorial participation 30 %: 0 % Final test 70 %: 100 % Total 100 %: 100 %                                3
Active lecture/seminar/workshop/tutorial participation: 20 % Final test: 80 %                                                             3
Active lecture/seminar/workshop/tutorial participation: 30 % Mid-term test(s): 30 % Final test: 40 %                                      3
Mid-term test(s): 30 % Final test: 70 %                                                                                                   3
Active lecture/seminar/workshop/tutorial participation: 6 % Term paper: 18 % Mid-term test(s): 38 % Final test: 26 % Home works: 12 %     2
Mid-term test(s): 20 % Final test: 80 %                                                                                                   2
Active lecture/seminar/workshop/tutorial participation: 10 % Mid-term test(s): 30 % Final test: 60 %                                      2
Final test: 100 %                                                                                                                         2
Active lecture/seminar/workshop/tutorial participation: 20 % Mid-term test(s): 30 % Final test: 50 %                                      2
Term paper: 30 % Mid-term test(s): 40 % Final oral exam: 30 %                                                                             2
Mid-term test(s) 40 %: 40 % Final test 60 %: 60 % Total 100 %: 100 %                                                                      2
Active lecture/seminar/workshop/tutorial participation 10 %: 10 % Mid-term test(s) 30 %: 30 % Final test 60 %: 60 % Total 100 %: 100 %    2
Term paper: 10 % Mid-term test(s): 20 % Final test: 70 %                                                                                  1
Active lecture/seminar/workshop/tutorial participation: 15 % Mid-term test(s): 15 % Final test: 60 % Case Studies: 10 %                   1
Mid-term test(s): 25 % Final oral exam: 60 % Home preparation and Moodle: 15 %                                                            1
Mid-term test(s): 20 % Final test: 40 % Final oral exam: 30 % Homework during the semester: 10 %                                          1
Active lecture/seminar/workshop/tutorial participation: 30 % Final test: 70 %                                                             1
Active lecture/seminar/workshop/tutorial participation: 14 % Term paper: 10 % Mid-term test(s): 16 % Final test: 60 %                     1
Mid-term test(s): 40 % Final test: 50 % Special requirements and details: 10 %                                                            1
Active lecture/seminar/workshop/tutorial participation: 25 % Mid-term test(s): 25 % Final test: 50 %                                      1
Term paper: 15 % Mid-term test(s): 15 % Final test: 70 %                                                                                  1
Special requirements and details 100 %: 100 % Total 100 %: 100 %                                                                          1
Active lecture/seminar/workshop/tutorial participation: 25 % Term paper: 13 % Presentation or defence: 12 % Final test: 50 %              1
Term paper: 10 % Mid-term test(s): 25 % Final test: 55 % Homeworks: 10 %                                                                  1
Mid-term test(s) 50 %: 0 % Final test 50 %: 0 % Total 100 %: 0 %                                                                          1
Term paper: 30 % Mid-term test(s): 20 % Final test: 50 %                                                                                  1
Name: count, dtype: int64

Partneři
Chybějící hodnoty: 555
Prázdné řetězce: 555

assessment_methods
Written Exam 0 %, Coursework 100 %, Practical Exam 0 %                                                                                                    35
Ordinary examination                                                                                                                                      30
Written Exam 70 %, Coursework 30 %, Practical Exam 0 %                                                                                                    13
Exam category: School Exam Form of assessment: Written School Exam - pen and paper Exam/hand-in semester: First Semester Weight: 100 Grouping: Individ    11
Exam category: School Exam Form of assessment: Written School Exam - digital Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Su    11
Written Exam 80 %, Coursework 20 %, Practical Exam 0 %                                                                                                     9
Written Exam 60 %, Coursework 40 %, Practical Exam 0 %                                                                                                     9
Written Exam 75 %, Coursework 25 %, Practical Exam 0 %                                                                                                     7
Exam category: School Exam Form of assessment: Structured Test Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Support material     7
Written Exam 50 %, Coursework 50 %, Practical Exam 0 %                                                                                                     5
Written Exam 90 %, Coursework 10 %, Practical Exam 0 %                                                                                                     3
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Group/Individual (1 - 3) Dura     3
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 30 Grouping: Group/Individual (1 - 4) Durat     2
Exam category: School Exam Form of assessment: Written School Exam - pen and paper Exam/hand-in semester: First Semester Weight: 30 Grouping: Individu     2
Written Exam 100 %, Coursework 0 %, Practical Exam 0 %                                                                                                     2
Written Exam 85 %, Coursework 15 %, Practical Exam 0 %                                                                                                     2
Written Exam 0 %, Coursework 70 %, Practical Exam 30 %                                                                                                     2
Exam category: Submission Form of assessment: Portfolio Assessment PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Individual Duration     2
Volunteering Experience and Reflection (30 %) Circular Economy Analysis (30 %) Final Exam (40 %)                                                           2
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 40 Grouping: Group/Individual (1 - 3) Durat     2
Written Exam 65 %, Coursework 35 %, Practical Exam 0 %                                                                                                     2
Exam category: Submission Form of assessment: Submission other than PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Group (4 - 6) Dura     2
Exam category: Submission Form of assessment: Submission other than PDF Exam/hand-in semester: First Semester Weight: 100 Grouping: Group/Individual (     2
Proposal (15 %) Final Presentation (20 %) Project Deliverables (25 %) Report (40 %)                                                                        2
Exam category: Submission Form of assessment: Submission PDF Exam/hand-in semester: First Semester Weight: 30 Grouping: Group/Individual (1 - 3) Durat     2
Midterm test (40 %) Essay (20 %) Final exam (40 %)                                                                                                         2
Tutorial Participation (15 %) Video Interview (Individual) (15 %) Survey Questionnaire (Individual) (10 %) Quantitative Analysis (Group Work) (30 %) F     1
Class test 1 (10 %) Individual Reflection (15 %) Class test 2 (10 %) Field trip attendance (5 %) Group Project (25 %) Final Examination (35 %)             1
Class Participation (10 %) Group Project (35 %) Final Examination (55 %)                                                                                   1
Individual Assignmnet (30 %) Group Assignment (30 %) Final Exam (40 %)                                                                                     1
Participation/Reflection (10 %) Interim Report (15 %) Presentation (5 %) Client Project (30 %) Final Examination (40 %)                                    1
Tutorial Attendance (10 %) Case Analysis 1 (12.5 %) Test (25 %) Case Analysis 2 (12.5 %) Final Examination (40 %)                                          1
Group Assignment (35 %) Individual Class Test (35 %) Individual Assignment (30 %)                                                                          1
Individual Service Encounters (20 %) Midterm Test (45 %) Team Project Report (25 %) Participation (10 %)                                                   1
Class Test (35 %) Individual Assignment (30 %) Group Project (35 %)                                                                                        1
Final Exam (45 %) Workshops Contributions (30 %) Reflective Report- Field Trip (25 %)                                                                      1
Bi-weekly Learn quizzes (20 %) Individual Presentation (20 %) Group Report (20 %) Final Exam (40 %)                                                        1
Marketing plan: proposal (15 %) Marketing plan: report & presentation (45 %) Final Examination (40 %)                                                      1
Group Assignments (50 %) Mid-term Test (20 %) Final Examination (30 %)                                                                                     1
Weekly Quizzes (on Learn) (20 %) Group Applied Case (30 %) Final Examination (50 %)                                                                        1
Name: count, dtype: int64

Ve sloupci `assessment_methods` nebyly identifikovány žádné chybějící hodnoty u dat VŠE. U partnerských univerzit se chybějící hodnoty vyskytovaly u části záznamů, protože některé zdroje informace o způsobu hodnocení neuváděly. V rámci čištění bylo provedeno pouze technické sjednocení textu, konkrétně doplnění chybějících mezer mezi textem a číselnými hodnotami, sjednocení zápisu procent a odstranění nadbytečných mezer. Obsahové informace o způsobu hodnocení nebyly dále upravovány, protože obsahují relevantní údaje o formě zkoušky, průběžném hodnocení, váhách jednotlivých částí hodnocení nebo skupinovém či individuálním charakteru hodnocení.

## Kontrola sloupce `literature`

In [59]:
# kontrola sloupce literature

print("VŠE")
print("Chybějící hodnoty:", vse_df["literature"].isna().sum())
print("Prázdné řetězce:", (vse_df["literature"].fillna("").str.strip() == "").sum())

display(
    vse_df["literature"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(30)
)

print("\nPartneři")
print("Chybějící hodnoty:", partner_df["literature"].isna().sum())
print("Prázdné řetězce:", (partner_df["literature"].fillna("").str.strip() == "").sum())

display(
    partner_df["literature"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(40)
)

VŠE
Chybějící hodnoty: 0
Prázdné řetězce: 0

literature
Basic: GÉRON, Aurélien. Hands-on machine learning with Scikit-Learn, Keras and TensorFlow : concepts, tools, and techniques to build intelligent syste    2
Basic: Votava, T. et al. (2024). Základy obchodního práva po rekodifikaci soukromého práva (6th ed.). Vydavatelství a nakladatelství Aleš Čenek, s.r.o    2
Basic: Grmelová, N., Andreisová, L., & Vaňkátová, T. (2019). An Introduction to Law (1st ed.). Powerprint, s.r.o. Recommended: CRAIG, Paul P.; DE BÚRC    2
Basic: Chiang, A. C., & Wainwright, K. (2005). Fundamental methods of mathematical economics. McGraw-Hill. Klůfa, J., & Kaspříková, N. (2013). Mathema    1
Basic: CIMLER, Petr; ZADRAŽILOVÁ, Dana. Retail management. Praha: Management Press, 2007. ISBN 978-80-7261-167-6.                                         1
Basic: Kubálek, T., & Kubálková, M. (2015). Program pro řízení projektů Microsoft Project 2013 (1st ed.). Nakladatelství Oeconomica. Kubálek, T., & Ku    1
Basic: Kubálek, T., & Kubálková, M. (2016). Databázový systém Microsoft Access 2016 (1st ed.). Nakladatelství Oeconomica. Kubálek, T. (2022). Manažers    1
Basic: Kubálek, T. (2022). Manažerská informatika. Nástroj týmové spolupráce Microsoft Teams (1st ed.). České vysoké učení technické v Praze, Masaryků    1
Basic: Karlíček, M. (2018). Základy marketingu. Grada Publishing, a.s. Recommended: Armstrong, G., & Kotler, P. (2004). Marketing. Grada. KOTLER, Phil    1
Basic: HNÁT, Pavel. Politická ekonomie globálních nerovnováh. 1. vyd. Praha: Nakladatelství Oeconomica, 2014. 232 p. ISBN 978-80-245-2023-0. Baldwin,     1
Basic: Sato, A. et al. (2021). Mezinárodní obchodní operace (1st ed.). Nakladatelství Oeconomica. Recommended: Machková, H., Sato, A., & Zamykalová, M    1
Basic: Srpová, J., Svobodová, I., Skopal, P., & Orlík, T. (2011). Podnikatelský plán a strategie (1st ed.). Grada Publishing. Recommended: Veber, J.,     1
Basic: Marek, P. (2009). Studijní průvodce financemi podniku. Ekopress. Recommended: Radová, J., Dvořák, P., & Málek, J. (2013). Finanční matematika p    1
Basic: Marek, P. (2009). Studijní průvodce financemi podniku. Ekopress. Recommended: Durčáková, J., Oceláková, P., & Valach, J. (2010). Investiční roz    1
Basic: Marek, P. (2009). Studijní průvodce financemi podniku. Ekopress. Recommended: MAREK, Petr. Rozdělování hospodářského výsledku a dividendová pol    1
Basic: Daft, R. L. (2016). Organization theory and design. Cengage Learning. SCHERMERHORN, John R. Exploring management. Hoboken: John Wiley & Sons, 2    1
Recommended: Allen, F., Brealey, R. A., & Myers, S. C. (2011). Principles of corporate finance. McGraw-Hill. Kaplan Publishing. Financial Management.     1
Basic: KOLDINSKÁ, Kristina; POLÁK, Petr; PRESSEROVÁ, Petra; TOMŠEJ, Jakub. Antidiskriminační zákon a související předpisy. Praha: Wolters Kluwer, 2023    1
Basic: BÁRTA, Vladimír; POSTLER, Milan; PÁTÍK, Ladislav. Retail marketing. Praha: Management Press, 2009. ISBN 978-80-7261-207-9. BÁRTA, Vladimír; POS    1
Basic: VYSEKALOVÁ, Jitka; MIKEŠ, Jiří. Reklama. Jak dělat reklamu. 4. vyd. Praha: Grada Publishing, a.s, 2018. 232 p. ISBN 978-80-247-5865-7. JESENSKÝ    1
Basic: DHAWAN, Erica. Digitální řeč těla : jak budovat důvěru a vztahy bez ohledu na vzdálenost. V Brně: CPress, 2023. ISBN 978-80-264-4687-3. DALE CA    1
Basic: JAY, Ros; TEMPLAR, Richard. Velká kniha manažerských dovedností. Praha: Grada, 2006. ISBN 80-247-1279-2. KOTTER, John P. Vedení procesu změny :    1
Basic: Bárta, V., Bártová, H., & Koudelka, J. (2007). Spotřebitel : (chování spotřebitele a jeho výzkum). Oeconomica. TAHAL, Radek. Marketingový výzku    1
Basic: Řezanková, H., & Löster, T. (2013). Základy statistiky (1st ed.). Oeconomica. Recommended: Langhamrová, J., Löster, T., & Řezanková, H. (2009).    1
Basic: Anthony, R. N., Govindarajan, V., Hartmann, F. G. H., Kraus, K., & Nilsson, G. (2021). Management control systems. McGraw-Hill. Crawford, L., G    1
Basic: Jackson, T. M., & Parkinson, R. (1989). Financial mathematics and statistics. Checkmate Gold. LUENBERGER, D. G. Investment Science. Oxford: Oxf    1
Basic: Office 2013 simplified [elektronický zdroj] : [step-by-step instructions for easy learning]. Indianapolis, Ind.: John Wiley & Sons, 2013. Recom    1
Basic: GRANT, David B. Fundamentals of logistics management. London: McGraw-Hill, 2006. ISBN 0-07-710894-9. Comtois, C., Rodrigue, J., & Slack, B. (20    1
Basic: Mankiw, N. G. (2012). Principles of economics. South-Western/Cengage Learning. Bernanke, B., & Frank, R. H. (2011). Principles of macroeconomic    1
Basic: COULTER, Mary K.; ROBBINS, Stephen P. Management. Boston: Pearson, 2016. ISBN 978-1-292-09020-7. SCHERMERHORN, John R. Exploring management. Ho    1
Name: count, dtype: Int64

Partneři
Chybějící hodnoty: 692
Prázdné řetězce: 692

literature
Textbooks / Resources There is no required text book for the course.                                                                                      2
Readings may be found either in the University library collection or accessed via The Library electronic journals on http://www.ed.ac.uk/schools-depar    2
Textbooks / Resources This course has weekly online readings for students which can be access via the library and uploaded onto Learn where possible.     2
Students will find the reading list on Learn.                                                                                                             2
Textbooks / Resources There is no prescribed textbook for the course, as the lecture notes, videos and learning modules should be sufficient for most     2
Mankiw and Taylor 'Economics'                                                                                                                             2
Textbooks / Resources Required Texts Shirley Carlon; Accounting: reporting, analysis and decision making ; 8th; John Wiley & Sons Australia Ltd, 2026.    1
Textbooks / Resources Required texts are: Thomson Reuters New Zealand Taxation 2026: Principles, Cases and Questions. Thomson Reuters New Zealand Taxa    1
Textbooks / Resources Required Texts Feehily, Ronan; Tiong, Raymond; An Introduction to the Law of Contract in New Zealand ; 7th; Thomson Reuters New     1
Textbooks / Resources Required Texts Eldenburg, Leslie; Management Accounting ; Fifth Edition; John Wiley & Sons Australia Ltd. This is available as a    1
Textbooks / Resources Required Texts Deegan, Craig; Financial Accounting ; 9th edition; McGraw Hill, 2020.                                                1
https://rl.talis.com/3/binorway/lists/807CAC6C-0617-670E-4C85-9F8A56FA59B3.html                                                                           1
Textbooks / Resources Required Texts Atrill, Peter; ACCT102 accounting and financial infomation ; 4th edition; Pearson.                                   1
https://rl.talis.com/3/binorway/lists/31B35019-216C-352E-BF7F-C0499CB49427.html                                                                           1
Textbooks / Resources Required Texts Deegan, Craig; Financial Accounting ; 9th edition; McGraw Hill Education (Australia) Pty Ltd, 2019.                  1
Textbooks / Resources Required Texts William Stallings & Lawrie Brown; Computer Security: Principles and Practice ; 3; Prentice Hall, 2015. - Other bo    1
Textbooks / Resources Required Texts Barrett, Jonathan; Understanding company law ; 5th; LexisNexis, 2025.                                                1
Textbooks / Resources Required Texts Leung, Philomena et al; Audit and assurance ; First edition; John Wiley & Sons Australia, 2019.                      1
Textbooks / Resources Required Texts Eldenburg, Leslie; Management accounting ; Fourth edition; John Wiley & Sons Australia, Ltd, 2020.                   1
Textbooks / Resources Required Texts Leung, Coram, Cooper, Redgen, Canestrari-Soh; Audit and Assurance ; 2nd; Wiley, 2023. Recommended Reading Pratt,     1
Textbooks / Resources Students will be provided with two booklets for the main part of the course.                                                        1
Textbooks / Resources Required: CCH, Income Tax Legislation, 2025 or 2026; or Thomson Reuters, Taxation Legislation Handbook 2025 or 2026 (your legisl    1
Textbooks / Resources - There is no formal recommended textbook, as we will use online resources and material supplied through Learn.                     1
Textbooks / Resources This can be bought as a physical book and is also available online at no charge at: https://runestone.academy/ns/books/published    1
Textbooks / Resources Jack Copeland et al., The Turing Guide (Oxford University Press, 2017). Copies are available in the University (UBS) Bookshop; t    1
Textbooks / Resources No textbooks are required, but see the following book for additional information: - Carol Critchlow and David Eck; Foundations o    1
Textbooks / Resources Recommended Reading: - Steven S. Skiena, The Algorithm Design Manual, Springer, 2nd Ed., 2008. - Cormen, Leiserson, Rivest, and     1
Textbooks / Resources There is no single book on which the course is based. Some useful references include: - William Stallings. Data and Computer Com    1
https://rl.talis.com/3/binorway/lists/35CEA017-C798-AE8E-4A66-B71F41116E53.html                                                                           1
Textbooks / Resources Recommended Reading Clarke, B.J; Introduction to Object-Oriented Systems Development with JADE ; 6th; Create-space Independent P    1
Textbooks / Resources Recommended Reading: 1. Designing with the Mind in Mind: Simple guide to understanding user interface design guidelines by Jeff     1
Textbooks / Resources Required Texts Rosen, Harvey S. , Gayer, Ted; Public finance ; Tenth edition; McGraw-Hill Education, 2014. Recommended Reading C    1
Textbooks / Resources Recommended Reading Benjamin C. Pierce; Types And Programming Language Hardcover ; The MIT Press, 2002 (An electronic copy of th    1
Textbooks / Resources Recommended Reading Blaise Barney; Introduction to Parallel Computing ; (Introduction to Parallel Computing (and other tutorials    1
Textbooks / Resources Recommended Reading Parkin, M., & Bade, R; Microeconomics ; Pearson, Australia, 2016. Some very readable books which give a very    1
Textbooks / Resources There is no prescribed text for this course. Instead the videos available at Marginal Revolution University (MRU) will act as yo    1
Textbooks / Resources Required Texts Hanley, N. H., Shogren, J. F., & White, B; Introduction to Environmental Economics ; 3rd; Oxford University Press    1
Textbooks / Resources Recommended reference books: Intermediate Microeconomics: A modern approach, by Hal Varian (published by Norton). Mathematics fo    1
Textbooks / Resources Required Texts Jeffrey Wooldridge; Introductory Econometrics: A Modern Approach ; 7th; Cengage Learning, 2020.                      1
Textbooks / Resources Required Texts Blanchard, Olivier; Macroeconomics ; Eighth edition, Global edition; Pearson, 2021. Other readings will be provid    1
Name: count, dtype: Int64

In [65]:
# čištění literature

LITERATURE_PLACEHOLDERS = [
    "-- item not defined --"
]

LITERATURE_ADMIN_PATTERNS = [
    r"^Students will find the reading list on Learn\.?$",

    r"^This course has weekly online readings for students.*$",

    r"^Readings may be found either in the University library collection.*$",

    r"^There is no required text book for the course\.?$",

    r"^There is no prescribed textbook for the course.*$",

    r"^A resource list will be published in Week 1\..*$",

    r"^A programme of study with topics and selected readings will be provided at the start of the course\.?$"
]


def clean_literature(text):

    if pd.isna(text):
        return pd.NA

    text = str(text)

    # sjednocení whitespace
    text = re.sub(r"\s+", " ", text).strip()

    # odstranění boilerplate prefixu
    text = re.sub(
        r"^Textbooks\s*/\s*Resources\s*",
        "",
        text,
        flags=re.IGNORECASE
    ).strip()

    # placeholdery
    if text in LITERATURE_PLACEHOLDERS:
        return pd.NA

    # administrativní / neobsahové informace
    for pattern in LITERATURE_ADMIN_PATTERNS:
        if re.match(pattern, text, flags=re.IGNORECASE):
            return pd.NA

    # čisté URL bez dalšího textu
    if re.fullmatch(r"https?://\S+", text):
        return pd.NA

    # prázdné hodnoty
    if text == "":
        return pd.NA

    return text


vse_df["literature"] = (
    vse_df["literature"]
    .apply(clean_literature)
)

partner_df["literature"] = (
    partner_df["literature"]
    .apply(clean_literature)
)

In [66]:
# kontrola po cleaningu literature

print("VŠE")
print("Chybějící hodnoty:", vse_df["literature"].isna().sum())
print("Prázdné řetězce:", (vse_df["literature"].fillna("").str.strip() == "").sum())

display(
    vse_df["literature"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(30)
)

print("\nPartneři")
print("Chybějící hodnoty:", partner_df["literature"].isna().sum())
print("Prázdné řetězce:", (partner_df["literature"].fillna("").str.strip() == "").sum())

display(
    partner_df["literature"]
    .dropna()
    .str[:150]
    .value_counts()
    .head(40)
)

VŠE
Chybějící hodnoty: 0
Prázdné řetězce: 0

literature
Basic: GÉRON, Aurélien. Hands-on machine learning with Scikit-Learn, Keras and TensorFlow : concepts, tools, and techniques to build intelligent syste    2
Basic: Grmelová, N., Andreisová, L., & Vaňkátová, T. (2019). An Introduction to Law (1st ed.). Powerprint, s.r.o. Recommended: CRAIG, Paul P.; DE BÚRC    2
Basic: Votava, T. et al. (2024). Základy obchodního práva po rekodifikaci soukromého práva (6th ed.). Vydavatelství a nakladatelství Aleš Čenek, s.r.o    2
Basic: Holman, R. (2005). Ekonomie. C.H. Beck. Recommended: Macáková, L. (2010). Mikroekonomie : základní kurs. Melandrium. Pavelka, T. (2007). Makroe    1
Basic: Mishkin, F. S. (2016). The economics of money, banking and financial markets. Pearson. Tresch, R. W. (2008). Public sector economics. Palgrave     1
Basic: Revenda, Z., Mandel, M., Kodera, J., Musílek, P., & Dvořák, P. (2023). Peněžní ekonomie a bankovnictví (7th ed.). Ekopress, s.r.o. Recommended:    1
Basic: Radová, J., Dvořák, P., & Málek, J. (2013). Finanční matematika pro každého (8th ed.). Grada Publishing. Radová, J. et al. (2011). Finanční mat    1
Basic: Maaytová, A., Ochrana, F., Pavel, J., Sedmihradská, L., Tepperová, J., & Vítek, L. (2015). Veřejné finance v teorii a praxi. Grada Publishing.     1
Basic: Randáková, M. et al. (2018). Finanční účetnictví v České republice po 1.1.2016 (podnikatelské subjekty). Oeconomica. Strouhal, J., Židlická, R.    1
Recommended: Head, A., & Watson, D. (2019). Corporate finance : principles and practice. Pearson. Vernimmen, P. (2014). Corporate finance : theory and    1
Basic: VESELÁ, Jitka. Investování na kapitálových trzích. Praha: Wolters Kluwer Česká republika, 2011. ISBN 978-80-7357-647-9. Veselá, J. (2005). Burz    1
Basic: VEJMĚLEK, Jan; ŽĎÁREK, Václav; CHALOUPKA, Lubomír; ROJÍČEK, Marek. Makroekonomická analýza - od teorie k aplikaci. 1. vyd. Zlín: Grada Publishi    1
Basic: FIBÍROVÁ, Jana; PETERA, Petr; WAGNER, Jaroslav; ŠOLJAKOVÁ, Libuše. Manažerské účetnictví : nástroje a metody. Praha: Wolters Kluwer ČR, 2019. I    1
Basic: Klůfa, J., & Pasáčková, J. (2023). Učebnice matematiky (1) pro studenty VŠE. Ekopress.                                                             1
Basic: Revenda, Z. (2011). Centrální bankovnictví. Management Press. ROJÍČEK, Marek; SPĚVÁČEK, Vojtěch; VEJMĚLEK, Jan; ZAMRAZILOVÁ, Eva; ŽĎÁREK, Václa    1
Basic: Durčáková, J., & Mandel, M. (2020). Mezinárodní finance a devizový trh. Ekopress. Eiteman, D. K., Moffett, M. H., & Stonehill, A. I. (2021). Mu    1
Basic: BRABENEC, Tomáš. Finanční analýza obchodních korporací. Jesenice: Ekopress, 2022. ISBN 978-80-87865-85-9. Recommended: ALVAREZ, Fernando; FRIDS    1
Basic: Cipra, T. (2013). Finanční ekonometrie. Ekopress. Arlt, J., & Arltová, M. (2009). Ekonomické časové řady. Professional Publishing. Recommended:    1
Basic: BLAHOVÁ, Naděžda. Rizika bank a jejich regulace. Jesenice: Ekopress, 2018. ISBN 978-80-87865-47-7. PFEIFER, Lukáš. Finanční stabilita bankovníh    1
Basic: Vančurová, A., & Zídková, H. (2022). Daňový systém ČR 2022 (1st ed.). Wolters Kluwer ČR. Recommended: texty, domácí úkoly a testy v Moodle         1
Basic: LOUŽEK, Marek. Kahneman, Daniel: Myšlení rychlé a pomalé. (Rec.: KAHNEMAN, Daniel. Myšlení : rychlé a pomalé. V Brně: Jan Melvil Publishing, 20    1
Basic: LEWIS, Lynne; TIETENBERG, Thomas H. Environmental and natural resource economics. New York: Routledge, Taylor & Francis Group, 2018. ISBN 978-1    1
Basic: Osborne, M. J. (2004). An introduction to game theory. Oxford University Press. Recommended: Robert Gibbons, A Primer in Game Theory, 1992         1
Basic: Cooter, R., & Ulen, T. (2008). Law & economics. Pearson/Addison Wesley. Recommended: FRIEDMAN, David D. Law's order : what economics has to do     1
Basic: BÉNASSY-QUÉRÉ, Agnès; COEURÉ, Benoît; JACQUET, Pierre; PISANI-FERRY, Jean. Economic policy : theory and practice. New York: Oxford University P    1
Basic: KYMLICKA, Will. Contemporary political philosophy : an introduction. Oxford: Clarendon, 1990. ISBN 0-19-827723-7. Recommended: HOBBES, Thomas;     1
Basic: WOOLDRIDGE, Jeffrey M. Introductory econometrics : a modern approach. [S.l.]: South-Western Cengage Learning, 2009. ISBN 978-0-324-78890-7. Rec    1
Basic: Zárybnická Žárová, M., Peprníčková, M., Vácha, P., Svitlík, J., & Čiperová, L. (2022). Essentials of financial accounting for non-specialists (    1
Recommended: Barnes, T.J., Peck, J., Sheppard, E.(eds.): The Wiley-Blackwel Companion to Economic Geography. Oxford. Blackwell Publishing Ltd., 2012.     1
Basic: Kubálek, T., & Topolová, I. (2006). MS Office XP - manažerská informatika. Textový procesor Microsoft Word, verze 2002 CZ. Oeconomica. Kubálek,    1
Name: count, dtype: int64

Partneři
Chybějící hodnoty: 708
Prázdné řetězce: 708

literature
Mankiw and Taylor 'Economics'                                                                                                                             2
Required Texts Atrill, Peter; ACCT102 accounting and financial infomation ; 4th edition; Pearson.                                                         1
The course follows the textbook: D. Besanko, D. Dranove, M. Shanley, S. Schaefer, Economics of Strategy, 6th Edition, Wiley, 2013. (Students are stron    1
There are many good text books available on organisation change and change management. The core text for the course is: Hughes, Mark (2010). Managing     1
Students will require to consult an up to date text book on employment law. The recommended text is: - Stephen Taylor and Astra Emir (2019) (5th Editi    1
J Rees & D Mullins (2016) The third sector delivering public services (Bristol University Press) M Kallman & T Clark (2016) The Third Sector (Universi    1
Recommended Reading: 1. S. P. Bradley, A. C. Hax, and T. L. Magnanti (1977), Applied Mathematical Programming, Addison-Wesley. [JCM Library shelfmark     1
Required: DePamphilis, D., 2019. Mergers, Acquisitions, and Other Restructuring Activities, 9th Edition. Academic Press. Recommended: Sudarsanam, S. 2    1
Meadows, D. H. (2008). Thinking in systems: A primer. Chelsea Green Publishing. https://wtf.tw/ref/meadows.pdf Mitchell, M. (2009). Complexity: A guid    1
James, G., Witten, D., Hastie, T., Tibshirani, R. (2017). An Introduction to Statistical Learning with Applications in R, Springer Texts in Statistics    1
The course relies on a selection of textbook chapters and articles. The core textbook for the course will be made available online before the start of    1
Core text(s) Clegg, S. (2023) Frameworks of Power. London: Sage. 2nd Edition Richards, S. (2019) The Prime Ministers: Reflections on Leadership from W    1
There is no required text for this course. Given the range of the topics covered and the constantly changing state of things, book chapters, journal a    1
There is no set textbook for this course, but the following books will prove useful: 1. Taha H. A., Operations Research - An Introduction, Pearson/Pre    1
Alcácer, J., J. Cantwell, L. Piscitello. 2016. Internationalization In The Information Age: A New Era For Places, Firms, And International Business Ne    1
A reading pack/list of core texts will be prepared for each lecture in accordance with the authors and themes named in the above course outline. This     1
Required textbooks - Frank & Cartwright, Microeconomics and Behaviour (3rd edition) Suggested textbook (for maths) - Renshaw, Maths for Economics (5th    1
Required textbooks - Frank & Cartwright, Microeconomics and Behaviour (2nd edition) Suggested textbook (for maths) - Renshaw, Maths for Economics (cur    1
Required textbooks - Gottfries, Macroeconomics (1st edition) Suggested textbook (for maths) - Renshaw, Maths for Economics (currently in 3rd edition,     1
Suggested textbook (for maths) - Renshaw, Maths for Economics (currently in 3rd edition, but any edition will do)                                         1
The course has a combination of one book plus a mixed set of readings that will mostly be provided on a lecture-by-lecture basis. The book (which will    1
Newbold, Carlson, Thorne "Statistics for Business and Economics: Global Edition"                                                                          1
Usunier, J., van Herk, H., & Lee, J. (2017). International and cross-cultural business research. SAGE Publications Ltd, https://dx.doi.org/10.4135/978    1
The main text for the course is Bodie, Z., Kane, A. and Marcus, A.J. 'Investments', 12th Edition 2020, McGraw-Hill The text recommended for further re    1
Angrist, J. D., & Pischke, J. S. (2009). Mostly harmless econometrics: An empiricist's companion. Princeton university press. Cunningham, Scott (2021)    1
Crawford, G., Crémer, J., Dinielli, D., Fletcher, A., Heidhues, P., Luca, M., Salz, T., Schnitzer, M., Scott Morton, F. M., Seim, K. and Sinkinson, M.    1
Bradley, Teresa. "Essential Mathematics for Economics and Business, 4th Edition" Wiley Publishing (2013). ISBN: 9781118358290                             1
Buchanan, A. and Huczynski, A. (2017) Organizational behaviour, 9th Edition, Harlow: Pearson. It is strongly recommended that this book should be purc    1
Recommended reference book Jonathan Berk and Peter DeMarzo, Corporate finance, 3rd edition (Global edition), 2013, Pearson Additional reference books     1
There will be a resource list comprising of academic journal articles, case studies, organisation and industry reports, as well as marketing and pract    1
Core texts: S Osborne (2021) Public Service Logic (Routledge, London) ISBN: 9781003009153 O Hughes (2018) Public Management and Administration 5th Edi    1
There is no required text-book for this course. Given the expansive nature of the topics covered, book chapters and academic journals will be primary     1
Required Text John R. Nofsinger, The Psychology of Investing, 7th edition, Routledge, 2022, ISBN 9780367748180 Only to be used for very few lectures a    1
The course is built upon periodical material. Journals most cited are: Business Ethics Quarterly (BEQ), Business Ethics: A European Review (BEER), Jou    1
Recommended: Hillier, F. S & Lieberman, J.G. (2015). Introduction to Operations Research. NY: McGraw-Hill. Further suggestions posted on Learn.           1
Indicative Reading List: Skene, K., 2015. Sustainable Economics. Routledge. R, W., 2019. The Circular Economy. Routledge. Benton, D., 2015. The Guide     1
There is no set text for this course. Participants will be given access to draft text book chapters written by the course lecturer and various journal    1
1. The main textbook for this course: S Martin, Industrial Organisation in Context, Oxford University Press, 2010. 2. J Lipczynski, J Wilson & J Godda    1
Joe O'Mahoney & Calvert Markham. Management Consulting, 2nd Edition. Oxford University Press. Available at Blackwells on Clerk Street. Other readings     1
Greene, F.J. (2020) Entrepreneurship theory and practice, Red Globe. ISBN : 9781137589569. Key journals: Entrepreneurship Theory and Practice; Harvard    1
Name: count, dtype: int64

Ve sloupci `literature` nebyly u dat VŠE identifikovány chybějící hodnoty. U partnerských univerzit se chybějící hodnoty vyskytovaly častěji, protože některé instituce literaturu vůbec neuváděly nebo ji zpřístupňovaly prostřednictvím externích systémů. V rámci čištění bylo provedeno sjednocení formátování textu, odstranění placeholder hodnot, samostatných URL odkazů bez další obsahové informace a vybraných administrativních formulací neobsahujících konkrétní bibliografické údaje. Samostatné URL odkazy byly odstraněny, protože bez doprovodného textu nepředstavovaly využitelnou informaci pro následné porovnávání sylabů. Bibliografické záznamy, doporučená literatura, odkazy uvedené jako součást textu a další obsahové informace byly ponechány beze změny.

## Kontrola obsahových atributů

In [69]:
# kontrola záznamů bez všech tří obsahových atributů podle univerzity

content_columns = ["aims", "course_content", "learning_outcomes"]

def all_content_missing(df):
    return df[content_columns].isna().all(axis=1)

print("VŠE")

display(
    vse_df.loc[
        all_content_missing(vse_df)
    ]
    .groupby("university")
    .size()
    .reset_index(name="missing_content_records")
)

print("\nPartneři")

display(
    partner_df.loc[
        all_content_missing(partner_df)
    ]
    .groupby("university")
    .size()
    .reset_index(name="missing_content_records")
)

VŠE

                                    university  missing_content_records
0  Prague University of Economics and Business                       30

Partneři

                 university  missing_content_records
0  University of Canterbury                        1

In [74]:
# odstranění záznamů bez dostupného obsahového atributu

vse_before = len(vse_df)
partner_before = len(partner_df)

vse_df = vse_df.loc[~all_content_missing(vse_df)].copy()
partner_df = partner_df.loc[~all_content_missing(partner_df)].copy()

print("Odstraněno z VŠE:", vse_before - len(vse_df))
print("Odstraněno z partnerských univerzit:", partner_before - len(partner_df))
print("Počet záznamů VŠE po odstranění:", len(vse_df))
print("Počet záznamů partnerů po odstranění:", len(partner_df))

Odstraněno z VŠE: 30
Odstraněno z partnerských univerzit: 1
Počet záznamů VŠE po odstranění: 103
Počet záznamů partnerů po odstranění: 898

Byly identifikovány a odstraněny záznamy, u nichž nebyl dostupný ani jeden z hlavních obsahových atributů (`aims`, `course_content`, `learning_outcomes`). Jednalo se především o část anglických verzí sylabů VŠE, ve kterých nebyly obsahové informace zveřejněny. Dataset tak obsahuje pouze předměty s alespoň jedním dostupným obsahovým atributem využitelným pro následné porovnávání sylabů.

## Finální statistika datasetu

In [77]:
# základní statistika datasetu - VŠE

print("VŠE")
print("Počet záznamů:", len(vse_df))
print("Počet sloupců:", vse_df.shape[1])

print("\nPočet záznamů podle akademického roku:")
display(
    vse_df["academic_year"]
    .fillna("missing")
    .value_counts()
    .rename_axis("academic_year")
    .reset_index(name="count")
)

print("\nDostupnost hlavních textových atributů:")
display(
    vse_df[
        [
            "aims",
            "course_content",
            "learning_outcomes",
            "assessment_methods",
            "literature"
        ]
    ]
    .notna()
    .sum()
    .rename("non_missing_count")
    .reset_index()
    .rename(columns={"index": "column"})
)

VŠE
Počet záznamů: 103
Počet sloupců: 17

Počet záznamů podle akademického roku:

  academic_year  count
0     2026/2027     75
1     2025/2026     28

Dostupnost hlavních textových atributů:

               column  non_missing_count
0                aims                103
1      course_content                102
2   learning_outcomes                102
3  assessment_methods                103
4          literature                103

In [80]:
# základní statistika datasetu - partnerské univerzity

print("Partneři")
print("Počet záznamů:", len(partner_df))
print("Počet sloupců:", partner_df.shape[1])

print("\nPočet záznamů podle univerzity:")
display(
    partner_df["university"]
    .value_counts()
    .rename_axis("university")
    .reset_index(name="count")
)

print("\nPočet záznamů podle země:")
display(
    partner_df["country"]
    .value_counts()
    .rename_axis("country")
    .reset_index(name="count")
)

print("\nPočet záznamů podle úrovně studia:")
display(
    partner_df["study_level"]
    .fillna("missing")
    .value_counts()
    .rename_axis("study_level")
    .reset_index(name="count")
)

print("\nPočet záznamů podle akademického roku:")
display(
    partner_df["academic_year"]
    .fillna("missing")
    .value_counts()
    .rename_axis("academic_year")
    .reset_index(name="count")
)

print("\nDostupnost hlavních textových atributů:")
text_columns = [
    "aims",
    "course_content",
    "learning_outcomes",
    "assessment_methods",
    "literature"
]

availability = (
    partner_df[text_columns]
    .notna()
    .sum()
    .rename("non_missing_count")
    .reset_index()
    .rename(columns={"index": "column"})
)

availability["availability_percent"] = (
    availability["non_missing_count"] / len(partner_df) * 100
).round(1)

display(availability)

Partneři
Počet záznamů: 898
Počet sloupců: 17

Počet záznamů podle univerzity:

                                           university  count
0  The Hong Kong University of Science and Technology    382
1                            University of Canterbury    188
2                        BI Norwegian Business School    126
3                             University of Edinburgh     98
4                                  Queen's University     71
5            Instituto Tecnológico Autónomo de México     33

Počet záznamů podle země:

          country  count
0       Hong Kong    382
1     New Zealand    188
2          Norway    126
3  United Kingdom     98
4          Canada     71
5          Mexico     33

Počet záznamů podle úrovně studia:

     study_level  count
0  undergraduate    772
1         master     71
2       bachelor     55

Počet záznamů podle akademického roku:

  academic_year  count
0     2025/2026    688
1     2026/2027    124
2     2024/2025     75
3     2016/2017      3
4     2023/2024      3
5     2019/2020      2
6     2018/2019      1
7     2015/2016      1
8          2019      1

Dostupnost hlavních textových atributů:

               column  non_missing_count  availability_percent
0                aims                897                  99.9
1      course_content                254                  28.3
2   learning_outcomes                734                  81.7
3  assessment_methods                344                  38.3
4          literature                191                  21.3

## Export finálních datasetů

In [79]:
# export finálních datasetů

vse_output_path = PROCESSED_DIR / "vse_syllabi_processed.csv"
partner_output_path = PROCESSED_DIR / "partner_syllabi_processed.csv"

vse_df.to_csv(vse_output_path, index=False, encoding="utf-8-sig")
partner_df.to_csv(partner_output_path, index=False, encoding="utf-8-sig")

print(f"VŠE dataset uložen do: {vse_output_path}")
print(f"Partnerský dataset uložen do: {partner_output_path}")

VŠE dataset uložen do: C:\Users\semlu\Documents\syllabus-similarity-thesis\data\processed\vse_syllabi_processed.csv
Partnerský dataset uložen do: C:\Users\semlu\Documents\syllabus-similarity-thesis\data\processed\partner_syllabi_processed.csv