In [9]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')

from dotenv import load_dotenv
import os
load_dotenv(PROJECT_ROOT / ".env")

api_key = os.getenv("OPENAI_API_KEY")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\semlu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\semlu\AppData\Roaming\nltk_data...
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\semlu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [40]:
!pip install sentence-transformers

Collecting sentence-transformers
  Using cached sentence_transformers-5.5.1-py3-none-any.whl.metadata (18 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Using cached transformers-5.9.0-py3-none-any.whl.metadata (33 kB)
Collecting huggingface-hub>=0.23.0 (from sentence-transformers)
  Using cached huggingface_hub-1.17.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: torch>=1.11.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (2.12.0)
Requirement already satisfied: numpy>=1.20.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: click>=8.4.0 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.27.0)
Requirement already satisfied: packaging>=20.9 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.20.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\semlu\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\semlu\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.5.0)
Requirement already satisfied: setuptools<82 in c:\users\semlu\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\semlu\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\semlu\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in c:\users\semlu\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: colorama in c:\users\semlu\anaconda3\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: regex>=2025.10.22 in c:\users\semlu\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\semlu\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: certifi in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.2)
Requirement already satisfied: idna in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.7)
Requirement already satisfied: sniffio in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\semlu\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\semlu\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\semlu\anaconda3\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\semlu\anaconda3\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\semlu\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\semlu\anaconda3\lib\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\semlu\anaconda3\lib\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\semlu\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.0)
Using cached sentence_transformers-5.5.1-py3-none-any.whl (588 kB)
Using cached huggingface_hub-1.17.0-py3-none-any.whl (671 kB)
Using cached transformers-5.9.0-py3-none-any.whl (10.8 MB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Installing collected packages: huggingface-hub, tokenizers, transformers, sentence-transformers
Successfully installed huggingface-hub-1.17.0 sentence-transformers-5.5.1 tokenizers-0.22.2 transformers-5.9.0

In [41]:
from sentence_transformers import SentenceTransformer

sbert_model = SentenceTransformer("all-MiniLM-L6-v2")

Collecting sentence-transformers
  Downloading sentence_transformers-5.5.1-py3-none-any.whl.metadata (18 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.9.0-py3-none-any.whl.metadata (33 kB)
Collecting huggingface-hub>=0.23.0 (from sentence-transformers)
  Downloading huggingface_hub-1.17.0-py3-none-any.whl.metadata (14 kB)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.12.0-cp312-cp312-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: numpy>=1.20.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\semlu\anaconda3\lib\site-packages (from sentence-transformers) (4.66.5)
Collecting click>=8.4.0 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2024.6.1)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.27.0)
Requirement already satisfied: packaging>=20.9 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in c:\users\semlu\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.20.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\semlu\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\semlu\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.5.0)
Requirement already satisfied: setuptools<82 in c:\users\semlu\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in c:\users\semlu\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in c:\users\semlu\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: colorama in c:\users\semlu\anaconda3\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Collecting regex>=2025.10.22 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading regex-2026.5.9-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: anyio in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: certifi in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.2)
Requirement already satisfied: idna in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.7)
Requirement already satisfied: sniffio in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.0)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers)
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\semlu\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\semlu\anaconda3\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\semlu\anaconda3\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\semlu\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\semlu\anaconda3\lib\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\semlu\anaconda3\lib\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\semlu\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.0)
Downloading sentence_transformers-5.5.1-py3-none-any.whl (588 kB)
   ---------------------------------------- 0.0/588.9 kB ? eta -:--:--
   --------------------------------------- 588.9/588.9 kB 10.5 MB/s eta 0:00:00
Downloading huggingface_hub-1.17.0-py3-none-any.whl (671 kB)
   ---------------------------------------- 0.0/671.5 kB ? eta -:--:--
   --------------------------------------- 671.5/671.5 kB 13.2 MB/s eta 0:00:00
Downloading torch-2.12.0-cp312-cp312-win_amd64.whl (123.0 MB)
   ---------------------------------------- 0.0/123.0 MB ? eta -:--:--
   - -------------------------------------- 6.0/123.0 MB 28.4 MB/s eta 0:00:05
   ---- ----------------------------------- 13.4/123.0 MB 32.3 MB/s eta 0:00:04
   ------ --------------------------------- 21.5/123.0 MB 34.0 MB/s eta 0:00:03
   --------- ------------------------------ 29.4/123.0 MB 34.5 MB/s eta 0:00:03
   ------------ --------------------------- 37.7/123.0 MB 35.8 MB/s eta 0:00:03
   --------------- ------------------------ 46.4/123.0 MB 36.4 MB/s eta 0:00:03
   ----------------- ---------------------- 55.1/123.0 MB 36.9 MB/s eta 0:00:02
   -------------------- ------------------- 63.4/123.0 MB 37.1 MB/s eta 0:00:02
   ----------------------- ---------------- 72.1/123.0 MB 37.7 MB/s eta 0:00:02
   -------------------------- ------------- 80.7/123.0 MB 37.6 MB/s eta 0:00:02
   ----------------------------- ---------- 89.7/123.0 MB 38.1 MB/s eta 0:00:01
   ------------------------------- -------- 98.0/123.0 MB 38.2 MB/s eta 0:00:01
   --------------------------------- ----- 105.6/123.0 MB 38.1 MB/s eta 0:00:01
   ------------------------------------ -- 114.3/123.0 MB 38.4 MB/s eta 0:00:01
   --------------------------------------  122.7/123.0 MB 38.4 MB/s eta 0:00:01
   --------------------------------------  122.9/123.0 MB 38.5 MB/s eta 0:00:01
   --------------------------------------  122.9/123.0 MB 38.5 MB/s eta 0:00:01
   --------------------------------------- 123.0/123.0 MB 33.3 MB/s eta 0:00:00
Downloading transformers-5.9.0-py3-none-any.whl (10.8 MB)
   ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
   -------------------- ------------------- 5.5/10.8 MB 23.9 MB/s eta 0:00:01
   ---------------------------------------- 10.8/10.8 MB 32.1 MB/s eta 0:00:00
Downloading click-8.4.1-py3-none-any.whl (116 kB)
Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 4.0/4.0 MB 29.7 MB/s eta 0:00:00
Downloading regex-2026.5.9-cp312-cp312-win_amd64.whl (277 kB)
Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 2.7/2.7 MB 31.9 MB/s eta 0:00:00
Downloading h11-0.14.0-py3-none-any.whl (58 kB)
Installing collected packages: sympy, safetensors, regex, hf-xet, h11, click, torch, huggingface-hub, tokenizers, transformers, sentence-transformers
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.2
    Uninstalling sympy-1.13.2:
      Successfully uninstalled sympy-1.13.2
  Attempting uninstall: regex
    Found existing installation: regex 2024.9.11
    Uninstalling regex-2024.9.11:
      Successfully uninstalled regex-2024.9.11
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: click
    Found existing installation: click 8.1.7
    Uninstalling click-8.1.7:
      Successfully uninstalled click-8.1.7
Successfully installed click-8.4.1 h11-0.14.0 hf-xet-1.5.0 huggingface-hub-1.17.0 regex-2026.5.9 safetensors-0.7.0 sentence-transformers-5.5.1 sympy-1.14.0 tokenizers-0.22.2 torch-2.12.0 transformers-5.9.0

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\semlu\anaconda3\Lib\site-packages\~egex'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
wsproto 1.3.2 requires h11<1,>=0.16.0, but you have h11 0.14.0 which is incompatible.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\semlu\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\semlu\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [78]:
!pip install openai

Collecting openai
  Downloading openai-2.38.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\semlu\anaconda3\lib\site-packages (from openai) (4.2.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\semlu\anaconda3\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\semlu\anaconda3\lib\site-packages (from openai) (0.27.0)
Collecting jiter<1,>=0.10.0 (from openai)
  Downloading jiter-0.15.0-cp312-cp312-win_amd64.whl.metadata (5.3 kB)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\semlu\anaconda3\lib\site-packages (from openai) (2.8.2)
Requirement already satisfied: sniffio in c:\users\semlu\anaconda3\lib\site-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in c:\users\semlu\anaconda3\lib\site-packages (from openai) (4.66.5)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\semlu\anaconda3\lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in c:\users\semlu\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: certifi in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\semlu\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\semlu\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\semlu\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\semlu\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.20.1)
Requirement already satisfied: colorama in c:\users\semlu\anaconda3\lib\site-packages (from tqdm>4->openai) (0.4.6)
Downloading openai-2.38.0-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 1.3/1.3 MB 23.5 MB/s eta 0:00:00
Downloading jiter-0.15.0-cp312-cp312-win_amd64.whl (197 kB)
Installing collected packages: jiter, openai
Successfully installed jiter-0.15.0 openai-2.38.0

In [79]:
from openai import OpenAI

client = OpenAI()

In [4]:
vse_df = pd.read_csv(PROCESSED_DIR / "vse_syllabi_processed.csv")
partner_df = pd.read_csv(PROCESSED_DIR / "partner_syllabi_processed.csv")

print("VŠE dataset:", vse_df.shape)
print("Partnerský dataset:", partner_df.shape)

display(vse_df.head(2))
display(partner_df.head(2))

VŠE dataset: (103, 17)
Partnerský dataset: (898, 17)

,course_title,course_code,university,country,source_url,academic_year,semester,semester_normalized,study_level,credits,credit_system,ects_credits,aims,course_content,learning_outcomes,assessment_methods,literature
0,Economics,2OP811,Prague University of Economics and Business,Czech Republic,https://insis-test.vse.cz/katalog/syllabus.pl?...,2026/2027,WS 2026/2027,winter,bachelor,6.0,ECTS,6.0,The couse is focused on basic economic categor...,1.Introduction into economics (allowance 1/0) ...,- identify the scope of economic research - de...,Term paper: 40 % Final test: 60 %,"Basic: Holman, R. (2005). Ekonomie. C.H. Beck...."
1,Financial Accounting,2OP816,Prague University of Economics and Business,Czech Republic,https://insis-test.vse.cz/katalog/syllabus.pl?...,2026/2027,WS 2026/2027,winter,bachelor,6.0,ECTS,6.0,Accounting as an information tool for the deci...,"1.Introduction to accounting: the nature, prin...",- understand the content of financial statemen...,Active lecture/seminar/workshop/tutorial parti...,"Basic: Janhuba, M., Míková, M., Roubíčková, J...."

,course_title,course_code,university,country,source_url,academic_year,semester,semester_normalized,study_level,credits,credit_system,ects_credits,aims,course_content,learning_outcomes,assessment_methods,literature
0,International Business,BST 2413,BI Norwegian Business School,Norway,https://programmeinfo.bi.no/nb/course/BST-2413...,2024/2025,Autumn,winter,bachelor,15.0,ECTS,15.0,This course prepares students for working in a...,The course content will be structured as below...,During the course students shall: Acquire know...,Exam category: Submission Form of assessment: ...,NaN
1,Mathematics for Data Science,EBA 1180,BI Norwegian Business School,Norway,https://programmeinfo.bi.no/nb/course/EBA-1180...,2024/2025,Autumn,winter,bachelor,7.5,ECTS,7.5,This is a basic course in mathematics. The cou...,Elementary algebra Mathematics of finance and ...,will have; Acquired a broad understanding of c...,Exam category: School Exam Form of assessment:...,NaN

In [5]:
print(vse_df.columns.tolist())

['course_title', 'course_code', 'university', 'country', 'source_url', 'academic_year', 'semester', 'semester_normalized', 'study_level', 'credits', 'credit_system', 'ects_credits', 'aims', 'course_content', 'learning_outcomes', 'assessment_methods', 'literature']

In [6]:
ATTRIBUTE = "course_content"

print("VŠE:")
print(vse_df[ATTRIBUTE].notna().sum())

print("\nPartneři:")
print(partner_df[ATTRIBUTE].notna().sum())

VŠE:
102

Partneři:
254

In [7]:
vse_df[ATTRIBUTE].dropna().head(3)

0    1.Introduction into economics (allowance 1/0) ...
1    1.Introduction to accounting: the nature, prin...
2    1.Marketing and commercial communication (allo...
Name: course_content, dtype: object

In [10]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_for_tfidf(text):
    if pd.isna(text) or text == '':
        return ''

    text = text.lower()
    text = re.sub(r'[^\w\s]', ' ', text)

    tokens = text.split()
    tokens = [t for t in tokens if t not in stop_words]
    tokens = [lemmatizer.lemmatize(t) for t in tokens]

    return ' '.join(tokens)

In [11]:
sample_text = partner_df["aims"].dropna().iloc[0]

print("PŮVODNÍ TEXT:")
print(sample_text[:700])

print("\nPREPROCESSED TEXT:")
print(preprocess_for_tfidf(sample_text)[:700])

PŮVODNÍ TEXT:
This course prepares students for working in an international business environment, by addressing critical macro-level factors in the environment and meso-level factors in the organization that are fundamental for a manager to be competent in international business. This course will provide students with knowledge of the institutional, organizational, and interpersonal factors and challenges that are critical to successful international business. The course begins with an overview of the global business environment and introduces the international organization and key decisions managers have to face when going international. The environmental and organizational context will provide the backd

PREPROCESSED TEXT:
course prepares student working international business environment addressing critical macro level factor environment meso level factor organization fundamental manager competent international business course provide student knowledge institutional organizational interpersonal factor challenge critical successful international business course begin overview global business environment introduces international organization key decision manager face going international environmental organizational context provide backdrop depth analysis culture management special focus placed cross cultural management global leadership international human resource management strategy structure international bu

In [12]:
ATTRIBUTE = "aims"

partner_texts = partner_df[ATTRIBUTE].apply(preprocess_for_tfidf)
vse_texts = vse_df[ATTRIBUTE].apply(preprocess_for_tfidf)

print("Počet partnerských textů:", len(partner_texts))
print("Neprázdné partnerské texty:", (partner_texts != "").sum())

print("Počet VŠE textů:", len(vse_texts))
print("Neprázdné VŠE texty:", (vse_texts != "").sum())

Počet partnerských textů: 898
Neprázdné partnerské texty: 897
Počet VŠE textů: 103
Neprázdné VŠE texty: 103

In [14]:
vse_df[
    vse_df["course_code"].str.startswith("4IT", na=False)
][["course_code", "course_title"]].sort_values("course_code")

   course_code                                       course_title
48      4IT419           Architectures of data-oriented solutions
50      4IT526                     Data warehousing and reporting
49      4IT529                           Competitive Intelligence
52      4IT533             Advanced machine learning and big data
47      4IT534  Applied deep learning and artificial intelligence
51      4IT535                        Machine learning operations
55      4IT537      Management of Data and Analytics for Business
54      4IT543              Presentation and communication skills
53      4IT553                 Practice in applied data analytics

In [15]:
VSE_CODE = "4IT537"

vse_course = vse_df.loc[
    vse_df["course_code"] == VSE_CODE
].iloc[0]

print("Kód:", vse_course["course_code"])
print("Název:", vse_course["course_title"])

vse_text = preprocess_for_tfidf(vse_course["aims"])

print("\nTF-IDF text:")
print(vse_text[:1000])

Kód: 4IT537
Název: Management of Data and Analytics for Business

TF-IDF text:
course focus managing data analytics strictly aligned business need cover method alignment business goal management service aimed data utilization management project data analytics field management financial organizational aspect data analytics application finally data governance data management discussed necessary requirement sustainable practice using data support business organization

In [16]:
vectorizer = TfidfVectorizer()

partner_matrix = vectorizer.fit_transform(partner_texts)
vse_vector = vectorizer.transform([vse_text])

scores = cosine_similarity(vse_vector, partner_matrix).flatten()

print("Počet výsledků:", len(scores))
print("Min score:", scores.min())
print("Max score:", scores.max())

Počet výsledků: 898
Min score: 0.0
Max score: 0.533748823302367

In [17]:
results = partner_df.copy()

results["similarity_score"] = scores

results = results.sort_values(
    "similarity_score",
    ascending=False
)

results[
    [
        "course_code",
        "course_title",
        "university",
        "similarity_score"
    ]
].head(20)

,course_code,course_title,university,similarity_score
878,COMM 392,Introduction to Data Management and Analytics ...,Queen's University,0.533749
631,DASC2210,A Survey on Big Data in Science and Society,The Hong Kong University of Science and Techno...,0.481339
607,RMBI1020,Business Intelligence for Data-Driven Decisions,The Hong Kong University of Science and Techno...,0.415380
214,INFO260,Data Management,University of Canterbury,0.406229
680,COMP4332,Big Data Mining and Management,The Hong Kong University of Science and Techno...,0.404528
427,ACCT4710,Accounting Analytics for Professional Accountants,The Hong Kong University of Science and Techno...,0.381548
507,MARK3620,Marketing Analytics,The Hong Kong University of Science and Techno...,0.352663
614,RMBI4310,Advanced Data Mining for Risk Management and B...,The Hong Kong University of Science and Techno...,0.344659
592,ISOM4860,Decision and Data Analytics in Financial Markets,The Hong Kong University of Science and Techno...,0.339254
115,TEM 0056,Applied Data Analytics,BI Norwegian Business School,0.327170
162,DATA101,Introduction to Data Science,University of Canterbury,0.306097
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.303549
632,DASC2220,Statistics and Probability for Data Analytics ...,The Hong Kong University of Science and Techno...,0.298416
608,RMBI3010,Data Analytics with R,The Hong Kong University of Science and Techno...,0.294223
559,ISOM3370,Big Data Technologies,The Hong Kong University of Science and Techno...,0.279217
166,DATA303,Computational Data Methods,University of Canterbury,0.273608
177,ECON314,"Economic Analysis of ""Big Data""",University of Canterbury,0.270762
895,COMM 461,Data Science for Business,Queen's University,0.262812
558,ISOM3360,Data Mining for Business Analytics,The Hong Kong University of Science and Techno...,0.259238
6,EDI 3400,Programming and Data Management,BI Norwegian Business School,0.258460

In [18]:
top3 = results.head(3)

for _, row in top3.iterrows():
    print("=" * 120)
    print(row["course_title"])
    print(row["university"])
    print(f"Score: {row['similarity_score']:.3f}")
    print()
    print(row["aims"][:1500])
    print()

========================================================================================================================
Introduction to Data Management and Analytics for Business
Queen's University
Score: 0.534

This course provides an introduction to data management and analytics for business. The course will present a systematic view of analytics with a key focus on using data for business intelligence and descriptive analytics as well as an overview of predictive analytics and how they are used by businesses for creating a competitive advantage. The course emphasizes the managerial aspects of analytics along with applications and implementation challenges, rather than technical issues (e.g. coding). The course will also focus on how to understand and manage data as an asset that is at the core of value creation in today's digital age, with emphasis on technical aspects such as data structure, data models, and data preparation and exploration, as well as management aspects such as data reliability and quality. Students will learn and apply relevant business intelligence and analytics concepts for solving various types of business problems using real data and practical business cases. After completing the course, students will be able to do the following: 1. Organize data for answering business questions through applications involving data modeling, extraction, querying, and transformation. 2. Describe issues that can arise with data and the resulting models and implement techniques to address them effectively. 3. Explain how organizations can use business intelligence and data analytics, AI, and machine learning for operational and strategic purposes. 4. Use technology tools to per

========================================================================================================================
A Survey on Big Data in Science and Society
The Hong Kong University of Science and Technology
Score: 0.481

To give students a broad understanding of the theoretical and practical aspects of data analytics and their applications in data-intensive fields. Topics include an introduction to the field of data science and Artificial Intelligence (AI), the data analytics workflow, and basic data analytics toolkits for making sense of data. Graded DI, PA or F.

========================================================================================================================
Business Intelligence for Data-Driven Decisions
The Hong Kong University of Science and Technology
Score: 0.415

Business intelligence is a discipline that comprises a set of theories, methodologies and processes to analyze business data with the aim of improving an organization's decision making, business planning and projection. Tomorrow’s employees and executives may not need the advanced skills of a data scientist, but they must be data literate. Therefore, there is a need to bring together data skills and business management by introducing a common core course, specializing at applying data analytics techniques to business scenarios for the implementation of business intelligence. The aim of this course is to introduce the general workflow of business intelligence and various applications of data analytics models in business scenarios. The course also focuses on an analysis of the strengths, limitations, causes and benefits of the use of business intelligence. The course also includes hands-on practical exercises by using data mining and statistics models on real business data sets.

In [19]:
print(vse_course["aims"])

The course focuses on managing data and analytics that is strictly aligned with business needs. It covers methods of alignment with business goals, management of services aimed at data utilization, management of projects in data and analytics field and management of financial and organizational aspects of data and analytics applications. Finally, Data Governance and Data Management are discussed as necessary requirements of the sustainable practice of using data to support business in an organization.

In [20]:
ATTRIBUTE = "course_content"

partner_texts = partner_df[ATTRIBUTE].apply(preprocess_for_tfidf)
vse_text = preprocess_for_tfidf(vse_course[ATTRIBUTE])

print("Neprázdné partnerské texty:", (partner_texts != "").sum())
print("VŠE text je prázdný:", vse_text == "")

print("\nVŠE course_content:")
print(vse_course[ATTRIBUTE][:1500])

Neprázdné partnerské texty: 254
VŠE text je prázdný: False

VŠE course_content:
Strategy and business-IT alignment - Strategy of data and analytics - contents and relationships to other components of an organization Services management - Design and implementation of data and analytics services - Evaluation of quality of services - Sourcing (sourcing strategy, tenders, RFPs) - Operations of the business analytics environment - Technological resources - analysis, evaluation, configuration Organizational aspects - Management of human resources for business analytics - Management of relationships with external partners - Organizational aspects impacting Agile architectures and Cloud / hybrid environment applicability Data Governance & Data Management - Data Governance principles, areas of Data Management - Data Management goals definition concerning organizational goals and strategy - Roles in Data Management, data ownership, identification of business requirements on data and their quality - Metadata management Principles and specifics of management of business analytics projects - Project phases and specifics of data-related projects Financial aspects - Management of business analytics economy - Cost calculations, specifics of economic and non-economic effects resulting from business analytics application - Infonomics and Data monetization

In [21]:
vectorizer = TfidfVectorizer()

partner_matrix = vectorizer.fit_transform(partner_texts)
vse_vector = vectorizer.transform([vse_text])

scores = cosine_similarity(vse_vector, partner_matrix).flatten()

results = partner_df.copy()
results["similarity_score"] = scores

results = results.sort_values(
    "similarity_score",
    ascending=False
)

results[
    [
        "course_code",
        "course_title",
        "university",
        "similarity_score"
    ]
].head(10)

,course_code,course_title,university,similarity_score
5,EBA 3630,Data Driven Management Accounting,BI Norwegian Business School,0.444575
315,BUST08032,Business Analytics and Information Systems,University of Edinburgh,0.398214
2,EBA 3400,"Programming, Data Extraction and Visualisation",BI Norwegian Business School,0.383450
58,GRA 4137,Data Protection and Ethics in the Modern Busin...,BI Norwegian Business School,0.354161
12,ELE 3709,Project Management,BI Norwegian Business School,0.308649
826,IIO-14180,Project Management and Evaluation,Instituto Tecnológico Autónomo de México,0.287752
96,TEM 0241,AI for Business,BI Norwegian Business School,0.263604
8,EDI 3500,Low Code Software Development,BI Norwegian Business School,0.254929
365,BUST10145,Predictive Analytics for Business,University of Edinburgh,0.229368
318,BUST08033,Business Research Methods I: Introduction to D...,University of Edinburgh,0.225663

In [22]:
top5 = results.head(5)

for _, row in top5.iterrows():
    print("=" * 120)
    print(row["course_title"])
    print(row["university"])
    print(f"Score: {row['similarity_score']:.3f}")
    print()
    print(row["course_content"][:2000])
    print()

========================================================================================================================
Data Driven Management Accounting
BI Norwegian Business School
Score: 0.445

In-house data External relevant data Extraction of data Decision analysis Management science Cost estimation for various profitability calculations Customer profitability analysis Accounting forensics Predictive analytics Visualisation of management accounting analytics

========================================================================================================================
Business Analytics and Information Systems
University of Edinburgh
Score: 0.398

This course discusses how business analytics and information system tools can be used in synergy to address a variety of business problems. As for the information system part, the emphasis is placed on 1. the illustration of how data can be modelled, stored and retrieved, 2. the application of data management tools to tackle business problems. The focus of business analytics is on: 1. the introduction of a range of prescriptive analytics tools which has been shown to aid decision-making in practice, 2. the utilisation of software with appropriate data to formulate and execute various models, 3. the explanation of the findings from modelling a managerial situation to the relevant stakeholders. Outline Content L 1. Data Management and Database Design L 2. Entity-relationship L 3. Structured Query Language L 4. Introduction to Linear Programming L 5. Sensitivity Analysis and Advanced Applications in Linear Programming L 6. Group Project Proposal Presentation L 7. Introduction to Decision Analysis L 8. Decision Analysis with Experiment L 9. Data Visualization L 10. Guest Speakers and revision Student Learning Experience The course is taught by means of lectures, computer labs, tutorials, and group activities. Lectures cover topics in information systems and data management, such as database design and SQL; as well as a number of business analytics techniques, such as linear programming, decision analysis and data visualisation. Computer labs let students acquire the skills that are necessary to apply these techniques in practice by using state of the art software packages. Tutorials provide an understanding of the theory underpinning the aforementioned techniques. Group activities are designed to let students experience challenges and opportunities that stem from the integration of decision support models and information systems.

========================================================================================================================
Programming, Data Extraction and Visualisation
BI Norwegian Business School
Score: 0.383

Python basics Programming environment. Variables and data types. Input and output. Control flow (conditionals and loops). Functions. Data extraction and visualization Reading and writing data. Data summarization and quality assessment. Subset selection and data manipulation. Data aggregation and statistics computation. Data visualization and interpretation.

========================================================================================================================
Data Protection and Ethics in the Modern Business Environment
BI Norwegian Business School
Score: 0.354

Fundamentals of privacy and data protection GDPR and regulation of automated decisions Data protection principles and ethical use of data Privacy by design and data protection impact assessments (DPIA) Rules on international transfer of data Data ethics in the digital economy The future of data protection in light of new technologies

========================================================================================================================
Project Management
BI Norwegian Business School
Score: 0.309

What is a project and project work Strategy and project management Selection and defining the project Time planning Cost and quality planning Organizational structures and teamwork Risk management Project leadership and management Stakeholder management Project control Scope management Contract administration Project completion and success evaluation

In [23]:
ATTRIBUTE = "learning_outcomes"

partner_texts = partner_df[ATTRIBUTE].apply(preprocess_for_tfidf)
vse_text = preprocess_for_tfidf(vse_course[ATTRIBUTE])

print("Neprázdné partnerské texty:", (partner_texts != "").sum())
print("VŠE text je prázdný:", vse_text == "")

print("\nVŠE learning_outcomes:")
print(vse_course[ATTRIBUTE])

Neprázdné partnerské texty: 734
VŠE text je prázdný: False

VŠE learning_outcomes:
understand and discuss: - Necessities of management of data and analytics alignment with goals of an organization and how to achieve it - Approaches to managing data-oriented services - Which organizational aspects are crucial concerning data management, what are the necessary roles and responsibilities that need to be established in an organization and for what purposes - How metadata supports the sustainable development of data environment in an organization - What are the specifics and options in the management of data-oriented projects

In [24]:
vectorizer = TfidfVectorizer()

partner_matrix = vectorizer.fit_transform(partner_texts)
vse_vector = vectorizer.transform([vse_text])

scores = cosine_similarity(vse_vector, partner_matrix).flatten()

results = partner_df.copy()
results["similarity_score"] = scores

results = results.sort_values(
    "similarity_score",
    ascending=False
)

results[
    [
        "course_code",
        "course_title",
        "university",
        "similarity_score"
    ]
].head(10)

,course_code,course_title,university,similarity_score
631,DASC2210,A Survey on Big Data in Science and Society,The Hong Kong University of Science and Techno...,0.263237
58,GRA 4137,Data Protection and Ethics in the Modern Busin...,BI Norwegian Business School,0.227079
680,COMP4332,Big Data Mining and Management,The Hong Kong University of Science and Techno...,0.217071
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.212698
639,DASC4300,Capstone Project for Data Analytics in Science,The Hong Kong University of Science and Techno...,0.210659
592,ISOM4860,Decision and Data Analytics in Financial Markets,The Hong Kong University of Science and Techno...,0.207683
561,ISOM3390,Business Programming in R,The Hong Kong University of Science and Techno...,0.204524
107,TEM 0203,Advanced Topics in Organisation Science,BI Norwegian Business School,0.195187
633,DASC3120,Data Structures for Data Analytics in Science,The Hong Kong University of Science and Techno...,0.192721
492,FINA4713,Introduction to Artificial Intelligence and Bi...,The Hong Kong University of Science and Techno...,0.186505

In [25]:
top5 = results.head(5)

for _, row in top5.iterrows():
    print("=" * 120)
    print(row["course_title"])
    print(row["university"])
    print(f"Score: {row['similarity_score']:.3f}")
    print()
    print(row["learning_outcomes"])
    print()

========================================================================================================================
A Survey on Big Data in Science and Society
The Hong Kong University of Science and Technology
Score: 0.263

1. Describe some examples in the field of Data Science. 2. Describe the data analytics workflow. 3. Assess how data science affects various aspects of science and society. 4. Apply suitable data analytics tools and algorithms to solve problems.

========================================================================================================================
Data Protection and Ethics in the Modern Business Environment
BI Norwegian Business School
Score: 0.227

This course will provide a comprehensive understanding of the legal and regulatory frameworks governing data protection and privacy. Students will learn about the essential requirements of data protection law in the European Union (EU) and the European Economic Area (EEA) , as well as the ethical implications and competitive advantages of using personal information in doing business. Throughout the course, students will: Learn about key terminology related to data protection Gain a basic understanding of the rules and principles for protecting privacy and personal data, particularly as laid down in EU and other international instruments. Gain detailed knowledge of the EU General Data Protection Regulation (GDPR) Aquire knowledge of the rules concerning the transfer of personal data to other countries Have a basic understanding of Norway`s obligation in the EEA agreement and European law and relevant case law Learn about the ethical challenges in modern business arising from the use of personal information and big data, such as monitoring, surveillance of individual behavior, and offering personalized services and products while limiting individuals' options and choices Explore the big data paradoxes of transparency, identity, and power. At the end of the course, the students will: Be able to differentiate between legitimate and problematic business behaviour in light of data protection rules Can design and advise on appropriate solutions to address privacy concerns in electronic commerce and Big data Be able to see the potential for technological development and discuss it based on regulations in privacy protection Be able to engage in informed debate on the necessary balance between the need of privacy and control over data in business settings and markets at large Be able to recognise the ethical challenges of Big data analytics and data sharing Have developed a special ethical consciousness when assessing data protection Be aware of the grey area outside the clearly defined rules. Understand the ethical principles for using data responsibly.

========================================================================================================================
Big Data Mining and Management
The Hong Kong University of Science and Technology
Score: 0.217

1. Identify big data issues such as mining and managing distributed data and sampling big data; and apply a range of cloud computing techniques to big data. 2. Apply data mining techniques to areas such as business intelligence, science and engineering. 3. Critically evaluate advanced literature in the data mining area.

========================================================================================================================
Introduction to Business Analytics
University of Canterbury
Score: 0.213

1) Demonstrate an understanding of key business data analytics concepts, tools and techniques. 2) To recognise and demonstrate an understanding of issues related to the use of business data for decision-making including data ownership and ethical considerations. 3) To recognise and analyse organisational problems and opportunities related to the role and use of data analytics in organisations. 4) To select and apply suitable techniques (e.g. regression, forecasting, cluster analysis, visualisation), extract meaningful insights from various data and make recommendations that align with the organisationsâ€™ context and objectives. 5) To perform key activities related to the analysis of organisational data and provide and communicate evidence-based recommendations.

========================================================================================================================
Capstone Project for Data Analytics in Science
The Hong Kong University of Science and Technology
Score: 0.211

1. Identify and describe a data-intensive field. 2. Develop a suitable data collection method. 3. Implement a comprehensive dashboard for performing descriptive analytics. 4. Apply suitable data-driven models for analysing data to identify problems and opportunities. 5. Evaluate data-driven insights, findings, and recommendations effectively through clear, structured, and professional oral presentations.

In [28]:
def tfidf_similarity(vse_text, partner_texts):
    vectorizer = TfidfVectorizer()

    partner_matrix = vectorizer.fit_transform(partner_texts)
    vse_vector = vectorizer.transform([vse_text])

    return cosine_similarity(vse_vector, partner_matrix).flatten()

In [27]:
WEIGHTS = {
    "aims": 0.40,
    "course_content": 0.35,
    "learning_outcomes": 0.25
}

In [29]:
aims_scores = tfidf_similarity(
    preprocess_for_tfidf(vse_course["aims"]),
    partner_df["aims"].apply(preprocess_for_tfidf)
)

content_scores = tfidf_similarity(
    preprocess_for_tfidf(vse_course["course_content"]),
    partner_df["course_content"].apply(preprocess_for_tfidf)
)

outcomes_scores = tfidf_similarity(
    preprocess_for_tfidf(vse_course["learning_outcomes"]),
    partner_df["learning_outcomes"].apply(preprocess_for_tfidf)
)

In [30]:
results = partner_df.copy()

results["aims_score"] = aims_scores
results["content_score"] = content_scores
results["outcomes_score"] = outcomes_scores

In [31]:
results["final_score_raw"] = (
    results["aims_score"] * WEIGHTS["aims"]
    + results["content_score"] * WEIGHTS["course_content"]
    + results["outcomes_score"] * WEIGHTS["learning_outcomes"]
)

In [34]:
def has_text(value):
    return not pd.isna(value) and str(value).strip() != ""

results["available_weight"] = 0.0

for attribute, weight in WEIGHTS.items():
    results["available_weight"] += results[attribute].apply(
        lambda x: weight if has_text(x) else 0
    )

In [35]:
results["weighted_sum"] = (
    results["aims_score"] * WEIGHTS["aims"] * results["aims"].apply(has_text)
    + results["content_score"] * WEIGHTS["course_content"] * results["course_content"].apply(has_text)
    + results["outcomes_score"] * WEIGHTS["learning_outcomes"] * results["learning_outcomes"].apply(has_text)
)

results["final_score"] = results["weighted_sum"] / results["available_weight"]

In [36]:
results.sort_values(
    "final_score",
    ascending=False
)[
    [
        "course_code",
        "course_title",
        "university",
        "aims_score",
        "content_score",
        "outcomes_score",
        "available_weight",
        "final_score"
    ]
].head(15)

,course_code,course_title,university,aims_score,content_score,outcomes_score,available_weight,final_score
878,COMM 392,Introduction to Data Management and Analytics ...,Queen's University,0.533749,0.000000,0.000000,0.40,0.533749
214,INFO260,Data Management,University of Canterbury,0.406229,0.000000,0.000000,0.40,0.406229
631,DASC2210,A Survey on Big Data in Science and Society,The Hong Kong University of Science and Techno...,0.481339,0.000000,0.263237,0.65,0.397454
680,COMP4332,Big Data Mining and Management,The Hong Kong University of Science and Techno...,0.404528,0.000000,0.217071,0.65,0.332429
427,ACCT4710,Accounting Analytics for Professional Accountants,The Hong Kong University of Science and Techno...,0.381548,0.000000,0.180872,0.65,0.304365
607,RMBI1020,Business Intelligence for Data-Driven Decisions,The Hong Kong University of Science and Techno...,0.415380,0.000000,0.091394,0.65,0.290770
5,EBA 3630,Data Driven Management Accounting,BI Norwegian Business School,0.229233,0.444575,0.168307,1.00,0.289371
592,ISOM4860,Decision and Data Analytics in Financial Markets,The Hong Kong University of Science and Techno...,0.339254,0.000000,0.207683,0.65,0.288650
166,DATA303,Computational Data Methods,University of Canterbury,0.273608,0.000000,0.000000,0.40,0.273608
614,RMBI4310,Advanced Data Mining for Risk Management and B...,The Hong Kong University of Science and Techno...,0.344659,0.000000,0.159284,0.65,0.273361
177,ECON314,"Economic Analysis of ""Big Data""",University of Canterbury,0.270762,0.000000,0.000000,0.40,0.270762
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.303549,0.000000,0.212698,0.65,0.268606
895,COMM 461,Data Science for Business,Queen's University,0.262812,0.000000,0.000000,0.40,0.262812
58,GRA 4137,Data Protection and Ethics in the Modern Busin...,BI Norwegian Business School,0.201953,0.354161,0.227079,1.00,0.261507
608,RMBI3010,Data Analytics with R,The Hong Kong University of Science and Techno...,0.294223,0.000000,0.165554,0.65,0.244735

In [37]:
results[
    [
        "course_title",
        "aims",
        "course_content",
        "learning_outcomes"
    ]
].iloc[878]

course_title         Introduction to Data Management and Analytics ...
aims                 This course provides an introduction to data m...
course_content                                                     NaN
learning_outcomes                                                  NaN
Name: 878, dtype: object

In [42]:
def minimal_clean_text(text):
    if pd.isna(text) or str(text).strip() == "":
        return ""

    text = str(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [43]:
sample_text = partner_df["aims"].dropna().iloc[0]

print("PŮVODNÍ TEXT:")
print(sample_text[:700])

print("\nMINIMAL CLEAN TEXT:")
print(minimal_clean_text(sample_text)[:700])

PŮVODNÍ TEXT:
This course prepares students for working in an international business environment, by addressing critical macro-level factors in the environment and meso-level factors in the organization that are fundamental for a manager to be competent in international business. This course will provide students with knowledge of the institutional, organizational, and interpersonal factors and challenges that are critical to successful international business. The course begins with an overview of the global business environment and introduces the international organization and key decisions managers have to face when going international. The environmental and organizational context will provide the backd

MINIMAL CLEAN TEXT:
This course prepares students for working in an international business environment, by addressing critical macro-level factors in the environment and meso-level factors in the organization that are fundamental for a manager to be competent in international business. This course will provide students with knowledge of the institutional, organizational, and interpersonal factors and challenges that are critical to successful international business. The course begins with an overview of the global business environment and introduces the international organization and key decisions managers have to face when going international. The environmental and organizational context will provide the backd

In [44]:
ATTRIBUTE = "aims"

partner_texts_sbert = partner_df[ATTRIBUTE].apply(minimal_clean_text).tolist()
vse_text_sbert = minimal_clean_text(vse_course[ATTRIBUTE])

partner_embeddings = sbert_model.encode(
    partner_texts_sbert,
    convert_to_numpy=True,
    show_progress_bar=True
)

vse_embedding = sbert_model.encode(
    [vse_text_sbert],
    convert_to_numpy=True
)

sbert_scores = cosine_similarity(
    vse_embedding,
    partner_embeddings
).flatten()

print("Počet výsledků:", len(sbert_scores))
print("Min score:", sbert_scores.min())
print("Max score:", sbert_scores.max())

Batches:   0%|          | 0/29 [00:00<?, ?it/s]

Počet výsledků: 898
Min score: -0.053975258
Max score: 0.7311598

In [45]:
sbert_results = partner_df.copy()
sbert_results["sbert_aims_score"] = sbert_scores

sbert_results = sbert_results.sort_values(
    "sbert_aims_score",
    ascending=False
)

sbert_results[
    [
        "course_code",
        "course_title",
        "university",
        "sbert_aims_score"
    ]
].head(15)

,course_code,course_title,university,sbert_aims_score
878,COMM 392,Introduction to Data Management and Analytics ...,Queen's University,0.731160
895,COMM 461,Data Science for Business,Queen's University,0.721355
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.716649
427,ACCT4710,Accounting Analytics for Professional Accountants,The Hong Kong University of Science and Techno...,0.703007
214,INFO260,Data Management,University of Canterbury,0.701276
167,DATA309,Data Science Capstone Project,University of Canterbury,0.672651
115,TEM 0056,Applied Data Analytics,BI Norwegian Business School,0.669124
607,RMBI1020,Business Intelligence for Data-Driven Decisions,The Hong Kong University of Science and Techno...,0.665496
638,DASC4020,Structured Query Language for Data Analytics,The Hong Kong University of Science and Techno...,0.662415
798,ADM-12350,Data-driven business decisions,Instituto Tecnológico Autónomo de México,0.639495
558,ISOM3360,Data Mining for Business Analytics,The Hong Kong University of Science and Techno...,0.614585
5,EBA 3630,Data Driven Management Accounting,BI Norwegian Business School,0.599534
631,DASC2210,A Survey on Big Data in Science and Society,The Hong Kong University of Science and Techno...,0.593906
163,DATA201,Data Wrangling,University of Canterbury,0.593460
639,DASC4300,Capstone Project for Data Analytics in Science,The Hong Kong University of Science and Techno...,0.589738

In [46]:
top5 = sbert_results.head(5)

for _, row in top5.iterrows():
    print("=" * 120)
    print(row["course_title"])
    print(row["university"])
    print(f"Score: {row['sbert_aims_score']:.3f}")
    print()
    print(row["aims"])
    print()

========================================================================================================================
Introduction to Data Management and Analytics for Business
Queen's University
Score: 0.731

This course provides an introduction to data management and analytics for business. The course will present a systematic view of analytics with a key focus on using data for business intelligence and descriptive analytics as well as an overview of predictive analytics and how they are used by businesses for creating a competitive advantage. The course emphasizes the managerial aspects of analytics along with applications and implementation challenges, rather than technical issues (e.g. coding). The course will also focus on how to understand and manage data as an asset that is at the core of value creation in today's digital age, with emphasis on technical aspects such as data structure, data models, and data preparation and exploration, as well as management aspects such as data reliability and quality. Students will learn and apply relevant business intelligence and analytics concepts for solving various types of business problems using real data and practical business cases. After completing the course, students will be able to do the following: 1. Organize data for answering business questions through applications involving data modeling, extraction, querying, and transformation. 2. Describe issues that can arise with data and the resulting models and implement techniques to address them effectively. 3. Explain how organizations can use business intelligence and data analytics, AI, and machine learning for operational and strategic purposes. 4. Use technology tools to perform descriptive data analytics, including data preparation, modeling, and visualization. 5. Build, train, test, evaluate, and deploy a machine learning model using graphical interface tools, and choose between competing models. 6. Communicate analytics results to managers and to a general business audience.

========================================================================================================================
Data Science for Business
Queen's University
Score: 0.721

The main goal of this course is to introduce data as one of the main business assets in the modern digital economy and data science tools as essential parts of the competitive strategy of the enterprise. The course will present a systematic view of analytics starting with descriptive for the essential understanding of the data, moving onto predictive to identify trends and opportunities, and completing the view with prescriptive to arrive at data-driven decisions

========================================================================================================================
Introduction to Business Analytics
University of Canterbury
Score: 0.717

Business analytics is a field that studies, interprets and visualises data to uncover patterns and insights that support informed decision-making. It produces actionable knowledge that can suggest how to improve business outcomes. This course introduces fundamental data analytics approaches and technology platforms widely used in industry practice. It addresses problems and opportunities comprehensively in order to translate business problems, specify questions, prepare, analyse, visualise data and recommend actions. Students apply tools and techniques to various business contexts such as marketing, accounting, finance and operations management.

========================================================================================================================
Accounting Analytics for Professional Accountants
The Hong Kong University of Science and Technology
Score: 0.703

Data analytics is reshaping the work of accountants. Applications of data analytics in accounting including: Auditing/Assurance - data analytics techniques used by accounting professionals and auditors nowadays to detect fraud and conduct forensic accounting. Enhancing Financial Reporting: more sophisticated data analytics tools can allow companies to link diverse financial and non-financial datasets and provide more comprehensive and rigorous financial reports to stakeholders. Managing risks: data analytics techniques such as continuous auditing and continuous monitoring can help accounting professionals assess and manage relevant risk levels within their organization. This course aims to provide students with knowledge of the nature and role of data analytics and enable students to apply and understand data analytics technologies to perform audit, enhance financial reporting, and minimize risks as accounting professionals.

========================================================================================================================
Data Management
University of Canterbury
Score: 0.701

The course introduces a range of topics that underpin data management in contemporary organisations. The first part of the course focuses on data architecture, data modelling, data administration, and data warehousing. The second part of the course introduces the concepts of Big Data. In its wider scope the course is designed to expose the students to real-life issues in data management and database management systems in the modern environment.

In [47]:
ATTRIBUTE = "course_content"

partner_texts_sbert = (
    partner_df[ATTRIBUTE]
    .fillna("")
    .apply(minimal_clean_text)
    .tolist()
)

vse_text_sbert = minimal_clean_text(
    vse_course[ATTRIBUTE]
)

print("Neprázdných partnerů:", sum(t != "" for t in partner_texts_sbert))
print("VŠE text prázdný:", vse_text_sbert == "")

Neprázdných partnerů: 254
VŠE text prázdný: False

In [48]:
partner_embeddings = sbert_model.encode(
    partner_texts_sbert,
    convert_to_numpy=True,
    show_progress_bar=True
)

vse_embedding = sbert_model.encode(
    [vse_text_sbert],
    convert_to_numpy=True
)

sbert_scores = cosine_similarity(
    vse_embedding,
    partner_embeddings
).flatten()

Batches:   0%|          | 0/29 [00:00<?, ?it/s]

In [49]:
sbert_results = partner_df.copy()

sbert_results["sbert_content_score"] = sbert_scores

sbert_results = sbert_results.sort_values(
    "sbert_content_score",
    ascending=False
)

sbert_results[
    [
        "course_code",
        "course_title",
        "university",
        "sbert_content_score"
    ]
].head(15)

,course_code,course_title,university,sbert_content_score
315,BUST08032,Business Analytics and Information Systems,University of Edinburgh,0.643415
5,EBA 3630,Data Driven Management Accounting,BI Norwegian Business School,0.559763
8,EDI 3500,Low Code Software Development,BI Norwegian Business School,0.525373
9,EDI 3510,Business Information Systems,BI Norwegian Business School,0.516011
317,BUST08056,Business Research Methods 2: Research Design a...,University of Edinburgh,0.493451
318,BUST08033,Business Research Methods I: Introduction to D...,University of Edinburgh,0.484180
12,ELE 3709,Project Management,BI Norwegian Business School,0.455190
93,TEM 0480,Operational Planning and Logistics Analytics,BI Norwegian Business School,0.424383
116,tem 0400,Business Economics,BI Norwegian Business School,0.420266
373,BUST10159,The Strategy of Digital Transformation,University of Edinburgh,0.419752
37,EXC 3580,Marketing Management and Strategy,BI Norwegian Business School,0.419321
329,BUST08057,Strategic Marketing Insights,University of Edinburgh,0.417505
363,BUST10092,Operations Strategy,University of Edinburgh,0.415268
365,BUST10145,Predictive Analytics for Business,University of Edinburgh,0.408504
796,ADM-12107,Business Strategy I,Instituto Tecnológico Autónomo de México,0.400882

In [50]:
ATTRIBUTE = "learning_outcomes"

partner_texts_sbert = (
    partner_df[ATTRIBUTE]
    .fillna("")
    .apply(minimal_clean_text)
    .tolist()
)

vse_text_sbert = minimal_clean_text(
    vse_course[ATTRIBUTE]
)

print("Neprázdných partnerů:", sum(t != "" for t in partner_texts_sbert))
print("VŠE text prázdný:", vse_text_sbert == "")

Neprázdných partnerů: 734
VŠE text prázdný: False

In [51]:
partner_embeddings = sbert_model.encode(
    partner_texts_sbert,
    convert_to_numpy=True,
    show_progress_bar=True
)

vse_embedding = sbert_model.encode(
    [vse_text_sbert],
    convert_to_numpy=True
)

sbert_scores = cosine_similarity(
    vse_embedding,
    partner_embeddings
).flatten()

Batches:   0%|          | 0/29 [00:00<?, ?it/s]

In [52]:
sbert_results = partner_df.copy()

sbert_results["sbert_outcomes_score"] = sbert_scores

sbert_results = sbert_results.sort_values(
    "sbert_outcomes_score",
    ascending=False
)

sbert_results[
    [
        "course_code",
        "course_title",
        "university",
        "sbert_outcomes_score"
    ]
].head(15)

,course_code,course_title,university,sbert_outcomes_score
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.640514
633,DASC3120,Data Structures for Data Analytics in Science,The Hong Kong University of Science and Techno...,0.629594
631,DASC2210,A Survey on Big Data in Science and Society,The Hong Kong University of Science and Techno...,0.606101
551,ISOM3260,Database Design and Administration,The Hong Kong University of Science and Techno...,0.571939
208,INFO123,Business Information Systems and Technology,University of Canterbury,0.544508
630,DASC2110,Object-oriented Programming for Data Analytics...,The Hong Kong University of Science and Techno...,0.541616
638,DASC4020,Structured Query Language for Data Analytics,The Hong Kong University of Science and Techno...,0.535826
365,BUST10145,Predictive Analytics for Business,University of Edinburgh,0.534790
639,DASC4300,Capstone Project for Data Analytics in Science,The Hong Kong University of Science and Techno...,0.513318
666,COMP3311,Database Management Systems,The Hong Kong University of Science and Techno...,0.509831
555,ISOM3330,Data Visualization and Visual Analytics,The Hong Kong University of Science and Techno...,0.502978
427,ACCT4710,Accounting Analytics for Professional Accountants,The Hong Kong University of Science and Techno...,0.500472
9,EDI 3510,Business Information Systems,BI Norwegian Business School,0.493233
700,COMP4651,Cloud Computing and Big Data Systems,The Hong Kong University of Science and Techno...,0.487463
260,MGMT272,Service Operations Management,University of Canterbury,0.485662

In [53]:
top5 = sbert_results.head(5)

for _, row in top5.iterrows():
    print("=" * 120)
    print(row["course_title"])
    print(row["university"])
    print(f"Score: {row['sbert_outcomes_score']:.3f}")
    print()
    print(row["learning_outcomes"])
    print()

========================================================================================================================
Introduction to Business Analytics
University of Canterbury
Score: 0.641

1) Demonstrate an understanding of key business data analytics concepts, tools and techniques. 2) To recognise and demonstrate an understanding of issues related to the use of business data for decision-making including data ownership and ethical considerations. 3) To recognise and analyse organisational problems and opportunities related to the role and use of data analytics in organisations. 4) To select and apply suitable techniques (e.g. regression, forecasting, cluster analysis, visualisation), extract meaningful insights from various data and make recommendations that align with the organisationsâ€™ context and objectives. 5) To perform key activities related to the analysis of organisational data and provide and communicate evidence-based recommendations.

========================================================================================================================
Data Structures for Data Analytics in Science
The Hong Kong University of Science and Technology
Score: 0.630

1. Describe and implement various data structures. 2. Describe and implement various searching and sorting algorithms. 3. Apply data structures and algorithms to solve data analytics problems effectively and efficiently.

========================================================================================================================
A Survey on Big Data in Science and Society
The Hong Kong University of Science and Technology
Score: 0.606

1. Describe some examples in the field of Data Science. 2. Describe the data analytics workflow. 3. Assess how data science affects various aspects of science and society. 4. Apply suitable data analytics tools and algorithms to solve problems.

========================================================================================================================
Database Design and Administration
The Hong Kong University of Science and Technology
Score: 0.572

1. Describe the database environment, benefits and risks, and development process. 2. Analyze how data should be represented and stored in the business information systems. 3. Design the data structure in conceptual and logical levels. 4. Manipulate the data with structured query language (SQL) and advanced SQL. 5. Apply programming skills and construct a realistic business information system.

========================================================================================================================
Business Information Systems and Technology
University of Canterbury
Score: 0.545

1. Explain the fundamental concepts of business information systems (IS), their role in organizations, and how IS can be leveraged to create business value, support strategic initiatives, and enhance decision making. 2. Analyse key business processes and the digital technologies that support them, including Collaboration Systems, Enterprise Resource Planning (ERP), Customer Relationship Management (CRM), Business Analytics, and Artificial Intelligence (AI) 3. Identify how digital innovation and digital business models associated with emerging technologies, ecosystems, and platforms transforms and create value in organizations and society. 4. Evaluate critical issues related to managing IS in organizations, such as the IS development process, information security, privacy, ethics, and IS governance. 5. Describe and assess key concepts, components, and technologies involved in selecting and implementing IS solutions, including hardware, software, and sustainable digital infrastructures. 6. Understand foundational database concepts to design, organize, manage, query, and visualize data using database management systems. 7. Develop proficiency in using business productivity tools such as presentation software, spreadsheets, data analytics tools, database applications, and generative AI assistants. 8. Demonstrate effective communication and presentation skills by creating and delivering a professional presentation tailored to IS and business audiences, using digital presentation tools

In [54]:
partner_texts = partner_df["aims"].fillna("").apply(minimal_clean_text).tolist()
vse_text = minimal_clean_text(vse_course["aims"])

partner_embeddings = sbert_model.encode(
    partner_texts,
    convert_to_numpy=True
)

vse_embedding = sbert_model.encode(
    [vse_text],
    convert_to_numpy=True
)

aims_scores = cosine_similarity(
    vse_embedding,
    partner_embeddings
).flatten()

In [55]:
partner_texts = partner_df["course_content"].fillna("").apply(minimal_clean_text).tolist()
vse_text = minimal_clean_text(vse_course["course_content"])

partner_embeddings = sbert_model.encode(
    partner_texts,
    convert_to_numpy=True
)

vse_embedding = sbert_model.encode(
    [vse_text],
    convert_to_numpy=True
)

content_scores = cosine_similarity(
    vse_embedding,
    partner_embeddings
).flatten()

In [56]:
partner_texts = partner_df["learning_outcomes"].fillna("").apply(minimal_clean_text).tolist()
vse_text = minimal_clean_text(vse_course["learning_outcomes"])

partner_embeddings = sbert_model.encode(
    partner_texts,
    convert_to_numpy=True
)

vse_embedding = sbert_model.encode(
    [vse_text],
    convert_to_numpy=True
)

outcomes_scores = cosine_similarity(
    vse_embedding,
    partner_embeddings
).flatten()

In [57]:
sbert_results = partner_df.copy()

sbert_results["aims_score"] = aims_scores
sbert_results["content_score"] = content_scores
sbert_results["outcomes_score"] = outcomes_scores

In [58]:
def has_text(value):
    return not pd.isna(value) and str(value).strip() != ""

In [59]:
sbert_results["available_weight"] = 0.0

for attribute, weight in WEIGHTS.items():
    sbert_results["available_weight"] += sbert_results[attribute].apply(
        lambda x: weight if has_text(x) else 0
    )

In [60]:
sbert_results["weighted_sum"] = (
    sbert_results["aims_score"] * WEIGHTS["aims"] * sbert_results["aims"].apply(has_text)
    + sbert_results["content_score"] * WEIGHTS["course_content"] * sbert_results["course_content"].apply(has_text)
    + sbert_results["outcomes_score"] * WEIGHTS["learning_outcomes"] * sbert_results["learning_outcomes"].apply(has_text)
)

In [61]:
sbert_results["final_score"] = (
    sbert_results["weighted_sum"]
    / sbert_results["available_weight"]
)

In [62]:
sbert_results.sort_values(
    "final_score",
    ascending=False
)[
    [
        "course_code",
        "course_title",
        "university",
        "aims_score",
        "content_score",
        "outcomes_score",
        "available_weight",
        "final_score"
    ]
].head(20)

,course_code,course_title,university,aims_score,content_score,outcomes_score,available_weight,final_score
878,COMM 392,Introduction to Data Management and Analytics ...,Queen's University,0.731160,-0.013371,-0.049615,0.40,0.731160
895,COMM 461,Data Science for Business,Queen's University,0.721355,-0.013371,-0.049615,0.40,0.721355
214,INFO260,Data Management,University of Canterbury,0.701276,-0.013371,-0.049615,0.40,0.701276
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.716649,-0.013371,0.640514,0.65,0.687366
167,DATA309,Data Science Capstone Project,University of Canterbury,0.672651,-0.013371,-0.049615,0.40,0.672651
427,ACCT4710,Accounting Analytics for Professional Accountants,The Hong Kong University of Science and Techno...,0.703007,-0.013371,0.500472,0.65,0.625109
638,DASC4020,Structured Query Language for Data Analytics,The Hong Kong University of Science and Techno...,0.662415,-0.013371,0.535826,0.65,0.613727
631,DASC2210,A Survey on Big Data in Science and Society,The Hong Kong University of Science and Techno...,0.593906,-0.013371,0.606101,0.65,0.598596
163,DATA201,Data Wrangling,University of Canterbury,0.593460,-0.013371,-0.049615,0.40,0.593460
607,RMBI1020,Business Intelligence for Data-Driven Decisions,The Hong Kong University of Science and Techno...,0.665496,-0.013371,0.461391,0.65,0.586994
220,INFO361,Business Intelligence and Analytics,University of Canterbury,0.566181,-0.013371,-0.049615,0.40,0.566181
551,ISOM3260,Database Design and Administration,The Hong Kong University of Science and Techno...,0.555901,-0.013371,0.571939,0.65,0.562069
639,DASC4300,Capstone Project for Data Analytics in Science,The Hong Kong University of Science and Techno...,0.589738,-0.013371,0.513318,0.65,0.560346
558,ISOM3360,Data Mining for Business Analytics,The Hong Kong University of Science and Techno...,0.614585,-0.013371,0.462738,0.65,0.556182
208,INFO123,Business Information Systems and Technology,University of Canterbury,0.538247,-0.013371,0.544508,0.65,0.540655
315,BUST08032,Business Analytics and Information Systems,University of Edinburgh,0.554226,0.643415,0.354355,1.00,0.535474
5,EBA 3630,Data Driven Management Accounting,BI Norwegian Business School,0.599534,0.559763,0.397258,1.00,0.535045
888,COMM 414,Management Control,Queen's University,0.530801,-0.013371,-0.049615,0.40,0.530801
277,MGMT374,Operations and Supply Chain Analytics,University of Canterbury,0.524498,-0.013371,-0.049615,0.40,0.524498
649,COMP1942,Exploring and Visualizing Data,The Hong Kong University of Science and Techno...,0.577649,-0.013371,0.437102,0.65,0.523593

In [63]:
def sbert_similarity_attribute(vse_text, partner_series):
    scores = np.full(len(partner_series), np.nan)

    valid_mask = (
        partner_series.notna()
        & (partner_series.astype(str).str.strip() != "")
    )

    valid_texts = (
        partner_series.loc[valid_mask]
        .apply(minimal_clean_text)
        .tolist()
    )

    partner_embeddings = sbert_model.encode(
        valid_texts,
        convert_to_numpy=True
    )

    vse_embedding = sbert_model.encode(
        [minimal_clean_text(vse_text)],
        convert_to_numpy=True
    )

    valid_scores = cosine_similarity(
        vse_embedding,
        partner_embeddings
    ).flatten()

    scores[valid_mask.to_numpy()] = valid_scores

    return scores

In [64]:
sbert_aims_scores = sbert_similarity_attribute(
    vse_course["aims"],
    partner_df["aims"]
)

sbert_content_scores = sbert_similarity_attribute(
    vse_course["course_content"],
    partner_df["course_content"]
)

sbert_outcomes_scores = sbert_similarity_attribute(
    vse_course["learning_outcomes"],
    partner_df["learning_outcomes"]
)

In [65]:
sbert_results = partner_df.copy()

sbert_results["aims_score"] = sbert_aims_scores
sbert_results["content_score"] = sbert_content_scores
sbert_results["outcomes_score"] = sbert_outcomes_scores

In [66]:
sbert_results["available_weight"] = 0.0

for attribute, weight in WEIGHTS.items():
    sbert_results["available_weight"] += (
        sbert_results[attribute]
        .notna()
        .astype(float)
        * weight
    )

In [67]:
sbert_results["weighted_sum"] = (
    sbert_results["aims_score"].fillna(0) * WEIGHTS["aims"]
    + sbert_results["content_score"].fillna(0) * WEIGHTS["course_content"]
    + sbert_results["outcomes_score"].fillna(0) * WEIGHTS["learning_outcomes"]
)

In [68]:
sbert_results["final_score"] = (
    sbert_results["weighted_sum"]
    / sbert_results["available_weight"]
)

In [69]:
sbert_results.sort_values(
    "final_score",
    ascending=False
)[
    [
        "course_code",
        "course_title",
        "university",
        "aims_score",
        "content_score",
        "outcomes_score",
        "available_weight",
        "final_score"
    ]
].head(20)

,course_code,course_title,university,aims_score,content_score,outcomes_score,available_weight,final_score
878,COMM 392,Introduction to Data Management and Analytics ...,Queen's University,0.731160,NaN,NaN,0.40,0.731160
895,COMM 461,Data Science for Business,Queen's University,0.721355,NaN,NaN,0.40,0.721355
214,INFO260,Data Management,University of Canterbury,0.701276,NaN,NaN,0.40,0.701276
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.716649,NaN,0.640514,0.65,0.687366
167,DATA309,Data Science Capstone Project,University of Canterbury,0.672651,NaN,NaN,0.40,0.672651
427,ACCT4710,Accounting Analytics for Professional Accountants,The Hong Kong University of Science and Techno...,0.703007,NaN,0.500472,0.65,0.625109
638,DASC4020,Structured Query Language for Data Analytics,The Hong Kong University of Science and Techno...,0.662415,NaN,0.535826,0.65,0.613727
631,DASC2210,A Survey on Big Data in Science and Society,The Hong Kong University of Science and Techno...,0.593906,NaN,0.606101,0.65,0.598596
163,DATA201,Data Wrangling,University of Canterbury,0.593460,NaN,NaN,0.40,0.593460
607,RMBI1020,Business Intelligence for Data-Driven Decisions,The Hong Kong University of Science and Techno...,0.665496,NaN,0.461391,0.65,0.586994
220,INFO361,Business Intelligence and Analytics,University of Canterbury,0.566181,NaN,NaN,0.40,0.566181
551,ISOM3260,Database Design and Administration,The Hong Kong University of Science and Techno...,0.555901,NaN,0.571939,0.65,0.562069
639,DASC4300,Capstone Project for Data Analytics in Science,The Hong Kong University of Science and Techno...,0.589738,NaN,0.513318,0.65,0.560346
558,ISOM3360,Data Mining for Business Analytics,The Hong Kong University of Science and Techno...,0.614585,NaN,0.462738,0.65,0.556182
208,INFO123,Business Information Systems and Technology,University of Canterbury,0.538247,NaN,0.544508,0.65,0.540655
315,BUST08032,Business Analytics and Information Systems,University of Edinburgh,0.554226,0.643415,0.354355,1.00,0.535474
5,EBA 3630,Data Driven Management Accounting,BI Norwegian Business School,0.599534,0.559763,0.397258,1.00,0.535045
888,COMM 414,Management Control,Queen's University,0.530801,NaN,NaN,0.40,0.530801
277,MGMT374,Operations and Supply Chain Analytics,University of Canterbury,0.524498,NaN,NaN,0.40,0.524498
649,COMP1942,Exploring and Visualizing Data,The Hong Kong University of Science and Techno...,0.577649,NaN,0.437102,0.65,0.523593

In [70]:
partner_df[
    partner_df["learning_outcomes"]
    .str.contains("should be", case=False, na=False)
][["course_title", "learning_outcomes"]]

,course_title,learning_outcomes
0,International Business,During the course students shall: Acquire know...
7,Communication in Action: Dialogue and Discourse,Students will acquire advanced knowledge about...
8,Low Code Software Development,"After completing the course, the candidate wil..."
11,Digital Innovation,"After completing the course, a candidate will ..."
12,Project Management,During the course student shall: Obtain knowle...
13,"Financial Bubbles, Crashes and Crises","During the course, students shall acquire: Kno..."
18,Financial Technology,"The student will Understand the history, curre..."
21,"Global Sustainability: Climate, Environment an...",The aim of this course is to provide an unders...
28,Business Communication - Culture and Ethics,Intercultural awareness. Students will acquire...
29,Business Communication - Negotiations and Pres...,The overall objective of this course is that s...
30,Economics I,"After completing the course, the candidate wil..."
32,Financial Reporting and Analysis,"After finishing the course, the student should..."
33,Organizational Behavior and Leadership,Learning outcomes - Knowledge Based on this co...
34,Economics II,should have knowledge of: The difference betwe...
35,Strategy,"After completion of this course, students shou..."
43,Supply Chain Management,After the course students shall have learned: ...
46,Analyses of Financial Data,The aims of this course are to: Introduce stud...
48,Financial Econometrics,"During the course, students should develop kno..."
49,"Recruitment, Selection and Development",Students should acquire knowledge on the costs...
50,Economic Psychology: Selected Topics,By the end of the course the student should be...
51,Advanced Human Resource Management,"By the end of the course, students should Have..."
55,Workplace Mistreatment and Conflict Resolution,"By the end of the course, candidate has advanc..."
56,"Pitching, Persuasion and Communication Skills","Specifically, students will acquire advanced k..."
57,International Entrepreneurship,Students should know the core theories of INV ...
60,Financial Accounting and Analysis,The students shall obtain knowledge about the ...
64,Economic Analysis of Topics in Law,will be familiar with the basic theoretical id...
67,Marketing Communication,the students will have a sound platform of kno...
71,Corporate Governance,The major objective of the course is to train ...
77,Environment and Sustainable Development,The aim of this course is to provide an unders...
80,Causal Inference with Big Data,"After having completed this course, students s..."
82,Art and Design Industries,On completion of the course the student should...
85,Marine Insurance,During the course students shall acquire: Insi...
90,Financial Reporting I,The course’s objectives are to make students f...
94,Strategic Risk Analysis,"After finishing this course, the student shoul..."
95,Supply Chain Management: Processes and Applica...,The student should be able to: understand the ...
97,Social Tensions and Connections in a Polarized...,"After completion of this course, students shou..."
99,Corporate Finance,Students at the end of the course should be ab...
101,Fundamentals of Corporate Finance,The students will acquire knowledge on: the im...
105,International Law,The student should have acquired: Good knowled...
106,Topics in the Economic Analysis of Law,Fint om læringsutbytte kan struktureres med ku...
116,Business Economics,This course aims to provide students with an u...
118,Economics for Finance,Provide students with an understanding of the ...
121,Numerical Methods for Pythons with Applications,After taking the course students should have a...
123,Financing Entrepreneurial and Corporate Ventures,Students should gain knowledge of the expandin...
124,Global Strategic Management,Students will: get an understanding of the fun...
194,Embedded Systems 1,"At the conclusion of this course, you should b..."
196,Business Finance,"At the end of the course, you should be able t..."
284,Services Marketing and Management,Upon completion of this course students should...
288,Advertising and Promotion Management,Students should be able to accomplish the foll...
292,Marketing for Behavioural Change,Upon completion of this course students should...
308,Multivariable Statistical Methods and Applicat...,Students from the courses STAT315 and STAT463 ...
551,Database Design and Administration,"1. Describe the database environment, benefits..."
797,Business Strategy II,After successfully completing this course stud...
809,Derivatives,"By the end of the class, you should at least h..."

In [74]:
partner_df["learning_outcomes"].str.contains(
    r"^students will",
    case=False,
    na=False
).sum()

8

In [75]:
partner_df["learning_outcomes"].str.contains(
    r"^will be able to",
    case=False,
    na=False
).sum()

2

In [76]:
from dotenv import load_dotenv
import os

load_dotenv(PROJECT_ROOT / ".env")

api_key = os.getenv("OPENAI_API_KEY")

print(api_key[:15])

sk-proj-sC3T0bX

In [80]:
response = client.embeddings.create(
    model="text-embedding-3-small",
    input="Data management and business analytics"
)

embedding = response.data[0].embedding

print(f"Délka embeddingu: {len(embedding)}")
print(embedding[:5])

Délka embeddingu: 1536
[0.00405120849609375, 0.038909912109375, 0.0882568359375, -0.017333984375, 0.023773193359375]

In [81]:
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"

def get_openai_embedding(text):
    response = client.embeddings.create(
        model=OPENAI_EMBEDDING_MODEL,
        input=text
    )
    return response.data[0].embedding

In [82]:
ATTRIBUTE = "aims"

vse_text = vse_df.loc[
    vse_df["course_code"] == "4IT537",
    ATTRIBUTE
].iloc[0]

print(vse_text[:500])

The course focuses on managing data and analytics that is strictly aligned with business needs. It covers methods of alignment with business goals, management of services aimed at data utilization, management of projects in data and analytics field and management of financial and organizational aspects of data and analytics applications. Finally, Data Governance and Data Management are discussed as necessary requirements of the sustainable practice of using data to support business in an organiz

In [84]:
vse_embedding = get_openai_embedding(vse_text)

print(len(vse_embedding))

1536

In [85]:
ATTRIBUTE = "aims"

partner_texts = partner_df[ATTRIBUTE].dropna()

print("Počet partnerských textů:", len(partner_texts))

total_chars = partner_texts.str.len().sum()
avg_chars = partner_texts.str.len().mean()

print("Celkem znaků:", total_chars)
print("Průměr znaků:", round(avg_chars))

Počet partnerských textů: 897
Celkem znaků: 494449
Průměr znaků: 551

In [86]:
ATTRIBUTE = "aims"

partner_texts = partner_df[ATTRIBUTE].dropna()
partner_indices = partner_texts.index.tolist()

print(len(partner_texts))

897

In [87]:
def get_openai_embeddings(texts, batch_size=100):
    embeddings = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]

        response = client.embeddings.create(
            model="text-embedding-3-small",
            input=batch
        )

        embeddings.extend(
            [item.embedding for item in response.data]
        )

        print(
            f"Hotovo {min(i + batch_size, len(texts))}/{len(texts)}"
        )

    return embeddings

In [88]:
partner_embeddings = get_openai_embeddings(
    partner_texts.tolist()
)

print(len(partner_embeddings))

Hotovo 100/897
Hotovo 200/897
Hotovo 300/897
Hotovo 400/897
Hotovo 500/897
Hotovo 600/897
Hotovo 700/897
Hotovo 800/897
Hotovo 897/897
897

In [89]:
partner_embeddings = np.array(partner_embeddings)

vse_embedding = np.array(get_openai_embedding(vse_text)).reshape(1, -1)

openai_scores = cosine_similarity(
    vse_embedding,
    partner_embeddings
).flatten()

print("Počet výsledků:", len(openai_scores))
print("Min score:", openai_scores.min())
print("Max score:", openai_scores.max())

Počet výsledků: 897
Min score: 0.12828219930314247
Max score: 0.7581550764666648

In [90]:
openai_results = partner_df.loc[partner_indices].copy()
openai_results["openai_aims_score"] = openai_scores

openai_results = openai_results.sort_values(
    "openai_aims_score",
    ascending=False
)

openai_results[
    [
        "course_code",
        "course_title",
        "university",
        "openai_aims_score"
    ]
].head(15)

,course_code,course_title,university,openai_aims_score
878,COMM 392,Introduction to Data Management and Analytics ...,Queen's University,0.758155
214,INFO260,Data Management,University of Canterbury,0.731719
895,COMM 461,Data Science for Business,Queen's University,0.698917
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.672088
558,ISOM3360,Data Mining for Business Analytics,The Hong Kong University of Science and Techno...,0.663187
607,RMBI1020,Business Intelligence for Data-Driven Decisions,The Hong Kong University of Science and Techno...,0.655140
115,TEM 0056,Applied Data Analytics,BI Norwegian Business School,0.653757
680,COMP4332,Big Data Mining and Management,The Hong Kong University of Science and Techno...,0.647407
545,ISOM2600,Introduction to Business Analytics,The Hong Kong University of Science and Techno...,0.643160
220,INFO361,Business Intelligence and Analytics,University of Canterbury,0.641752
507,MARK3620,Marketing Analytics,The Hong Kong University of Science and Techno...,0.639175
427,ACCT4710,Accounting Analytics for Professional Accountants,The Hong Kong University of Science and Techno...,0.636578
798,ADM-12350,Data-driven business decisions,Instituto Tecnológico Autónomo de México,0.622188
16,ELE 3781,Mathematics - Elective,BI Norwegian Business School,0.615505
559,ISOM3370,Big Data Technologies,The Hong Kong University of Science and Techno...,0.614912

In [92]:
print(
    openai_results.loc[
        openai_results["course_code"] == "ELE 3781",
        "aims"
    ].iloc[0]
)

This elective course is based on the Master's course GRA 6035 Mathematics, and is intended for students at the programme Bachelor of Data Science for Business, aiming for admission to the Master of Data Science for Business. The language of mathematics is extensively used to analyse problems in business, economics and finance, and mathematical models, theories, and methods are extensively used to solve problems. The mathematical requirements of students in Business Analytics go beyond the material usually taught in other undergraduate courses, and this elective course will teach the student more advanced mathematical models, theories, and methods. Topics include linear algebra and matrix methods, optimisation in several real variables, differential and difference equations.

In [93]:
ATTRIBUTE = "course_content"

partner_texts = partner_df[ATTRIBUTE].dropna()
partner_indices = partner_texts.index.tolist()

print("Počet partnerských textů:", len(partner_texts))

total_chars = partner_texts.str.len().sum()
avg_chars = partner_texts.str.len().mean()

print("Celkem znaků:", total_chars)
print("Průměr znaků:", round(avg_chars))

Počet partnerských textů: 254
Celkem znaků: 269000
Průměr znaků: 1059

In [94]:
partner_embeddings = get_openai_embeddings(
    partner_texts.tolist()
)

print(len(partner_embeddings))

Hotovo 100/254
Hotovo 200/254
Hotovo 254/254
254

In [95]:
vse_text = vse_df.loc[
    vse_df["course_code"] == "4IT537",
    ATTRIBUTE
].iloc[0]

vse_embedding = get_openai_embedding(vse_text)

partner_embeddings = np.array(partner_embeddings)
vse_embedding = np.array(vse_embedding).reshape(1, -1)

openai_scores = cosine_similarity(
    vse_embedding,
    partner_embeddings
).flatten()

print("Počet výsledků:", len(openai_scores))
print("Min score:", openai_scores.min())
print("Max score:", openai_scores.max())

Počet výsledků: 254
Min score: 0.1994409685434121
Max score: 0.6323852294971442

In [96]:
openai_content_results = partner_df.loc[partner_indices].copy()
openai_content_results["openai_content_score"] = openai_scores

openai_content_results = openai_content_results.sort_values(
    "openai_content_score",
    ascending=False
)

openai_content_results[
    [
        "course_code",
        "course_title",
        "university",
        "openai_content_score"
    ]
].head(15)

,course_code,course_title,university,openai_content_score
315,BUST08032,Business Analytics and Information Systems,University of Edinburgh,0.632385
5,EBA 3630,Data Driven Management Accounting,BI Norwegian Business School,0.573533
373,BUST10159,The Strategy of Digital Transformation,University of Edinburgh,0.529203
329,BUST08057,Strategic Marketing Insights,University of Edinburgh,0.522947
368,CMSE10002,Strategic Management,University of Edinburgh,0.519675
363,BUST10092,Operations Strategy,University of Edinburgh,0.518740
37,EXC 3580,Marketing Management and Strategy,BI Norwegian Business School,0.518193
96,TEM 0241,AI for Business,BI Norwegian Business School,0.512872
9,EDI 3510,Business Information Systems,BI Norwegian Business School,0.508026
8,EDI 3500,Low Code Software Development,BI Norwegian Business School,0.507190
116,tem 0400,Business Economics,BI Norwegian Business School,0.506739
361,BUST10134,Mathematical Programming in Advanced Analytics,University of Edinburgh,0.498903
52,GRA 2269,Leading in Organizations Using Intelligent Dec...,BI Norwegian Business School,0.494310
108,TEM 0521,Agile Management and Collaborative Leadership,BI Norwegian Business School,0.476129
796,ADM-12107,Business Strategy I,Instituto Tecnológico Autónomo de México,0.475812

In [97]:
for code in ["BUST08032", "EBA 3630"]:
    row = openai_content_results[
        openai_content_results["course_code"] == code
    ].iloc[0]

    print(row["course_title"])
    print()
    print(row["course_content"])
    print("\n" + "="*100 + "\n")

Business Analytics and Information Systems

This course discusses how business analytics and information system tools can be used in synergy to address a variety of business problems. As for the information system part, the emphasis is placed on 1. the illustration of how data can be modelled, stored and retrieved, 2. the application of data management tools to tackle business problems. The focus of business analytics is on: 1. the introduction of a range of prescriptive analytics tools which has been shown to aid decision-making in practice, 2. the utilisation of software with appropriate data to formulate and execute various models, 3. the explanation of the findings from modelling a managerial situation to the relevant stakeholders. Outline Content L 1. Data Management and Database Design L 2. Entity-relationship L 3. Structured Query Language L 4. Introduction to Linear Programming L 5. Sensitivity Analysis and Advanced Applications in Linear Programming L 6. Group Project Proposal Presentation L 7. Introduction to Decision Analysis L 8. Decision Analysis with Experiment L 9. Data Visualization L 10. Guest Speakers and revision Student Learning Experience The course is taught by means of lectures, computer labs, tutorials, and group activities. Lectures cover topics in information systems and data management, such as database design and SQL; as well as a number of business analytics techniques, such as linear programming, decision analysis and data visualisation. Computer labs let students acquire the skills that are necessary to apply these techniques in practice by using state of the art software packages. Tutorials provide an understanding of the theory underpinning the aforementioned techniques. Group activities are designed to let students experience challenges and opportunities that stem from the integration of decision support models and information systems.

====================================================================================================

Data Driven Management Accounting

In-house data External relevant data Extraction of data Decision analysis Management science Cost estimation for various profitability calculations Customer profitability analysis Accounting forensics Predictive analytics Visualisation of management accounting analytics

====================================================================================================

In [98]:
ATTRIBUTE = "learning_outcomes"

partner_texts = partner_df[ATTRIBUTE].dropna()
partner_indices = partner_texts.index.tolist()

print("Počet partnerských textů:", len(partner_texts))

total_chars = partner_texts.str.len().sum()
avg_chars = partner_texts.str.len().mean()

print("Celkem znaků:", total_chars)
print("Průměr znaků:", round(avg_chars))

Počet partnerských textů: 734
Celkem znaků: 520679
Průměr znaků: 709

In [99]:
partner_embeddings = get_openai_embeddings(
    partner_texts.tolist()
)

print(len(partner_embeddings))

Hotovo 100/734
Hotovo 200/734
Hotovo 300/734
Hotovo 400/734
Hotovo 500/734
Hotovo 600/734
Hotovo 700/734
Hotovo 734/734
734

In [100]:
vse_text = vse_df.loc[
    vse_df["course_code"] == "4IT537",
    ATTRIBUTE
].iloc[0]

print(vse_text)

understand and discuss: - Necessities of management of data and analytics alignment with goals of an organization and how to achieve it - Approaches to managing data-oriented services - Which organizational aspects are crucial concerning data management, what are the necessary roles and responsibilities that need to be established in an organization and for what purposes - How metadata supports the sustainable development of data environment in an organization - What are the specifics and options in the management of data-oriented projects

In [101]:
vse_embedding = get_openai_embedding(vse_text)

print(len(vse_embedding))

1536

In [102]:
partner_embeddings = np.array(partner_embeddings)

vse_embedding = np.array(
    vse_embedding
).reshape(1, -1)

openai_scores = cosine_similarity(
    vse_embedding,
    partner_embeddings
).flatten()

print("Počet výsledků:", len(openai_scores))
print("Min score:", openai_scores.min())
print("Max score:", openai_scores.max())

Počet výsledků: 734
Min score: 0.15664111050480983
Max score: 0.636933527202246

In [103]:
openai_outcomes_results = partner_df.loc[
    partner_indices
].copy()

openai_outcomes_results[
    "openai_outcomes_score"
] = openai_scores

openai_outcomes_results = (
    openai_outcomes_results
    .sort_values(
        "openai_outcomes_score",
        ascending=False
    )
)

openai_outcomes_results[
    [
        "course_code",
        "course_title",
        "university",
        "openai_outcomes_score"
    ]
].head(15)

,course_code,course_title,university,openai_outcomes_score
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.636934
614,RMBI4310,Advanced Data Mining for Risk Management and B...,The Hong Kong University of Science and Techno...,0.574518
365,BUST10145,Predictive Analytics for Business,University of Edinburgh,0.567909
639,DASC4300,Capstone Project for Data Analytics in Science,The Hong Kong University of Science and Techno...,0.556175
563,ISOM3530,Business Data Analytics,The Hong Kong University of Science and Techno...,0.550744
532,MGMT4290,HR Analytics,The Hong Kong University of Science and Techno...,0.549727
558,ISOM3360,Data Mining for Business Analytics,The Hong Kong University of Science and Techno...,0.549724
427,ACCT4710,Accounting Analytics for Professional Accountants,The Hong Kong University of Science and Techno...,0.548004
633,DASC3120,Data Structures for Data Analytics in Science,The Hong Kong University of Science and Techno...,0.531246
638,DASC4020,Structured Query Language for Data Analytics,The Hong Kong University of Science and Techno...,0.529579
135,ACCT316,Public Management and Governance,University of Canterbury,0.527765
649,COMP1942,Exploring and Visualizing Data,The Hong Kong University of Science and Techno...,0.524639
631,DASC2210,A Survey on Big Data in Science and Society,The Hong Kong University of Science and Techno...,0.519420
555,ISOM3330,Data Visualization and Visual Analytics,The Hong Kong University of Science and Techno...,0.518492
260,MGMT272,Service Operations Management,University of Canterbury,0.517976

In [104]:
aims_scores = openai_results[
    ["course_code", "openai_aims_score"]
]

content_scores = openai_content_results[
    ["course_code", "openai_content_score"]
]

outcomes_scores = openai_outcomes_results[
    ["course_code", "openai_outcomes_score"]
]

In [105]:
results = partner_df.copy()

results = results.merge(
    aims_scores,
    on="course_code",
    how="left"
)

results = results.merge(
    content_scores,
    on="course_code",
    how="left"
)

results = results.merge(
    outcomes_scores,
    on="course_code",
    how="left"
)

In [106]:
results["available_weight"] = 0.0

results["available_weight"] += (
    results["openai_aims_score"].notna().astype(float)
    * WEIGHTS["aims"]
)

results["available_weight"] += (
    results["openai_content_score"].notna().astype(float)
    * WEIGHTS["course_content"]
)

results["available_weight"] += (
    results["openai_outcomes_score"].notna().astype(float)
    * WEIGHTS["learning_outcomes"]
)

In [107]:
results["weighted_sum"] = (
    results["openai_aims_score"].fillna(0) * WEIGHTS["aims"]
    + results["openai_content_score"].fillna(0) * WEIGHTS["course_content"]
    + results["openai_outcomes_score"].fillna(0) * WEIGHTS["learning_outcomes"]
)

In [108]:
results["final_score"] = (
    results["weighted_sum"] / results["available_weight"]
)

In [109]:
results.sort_values(
    "final_score",
    ascending=False
)[
    [
        "course_code",
        "course_title",
        "university",
        "openai_aims_score",
        "openai_content_score",
        "openai_outcomes_score",
        "available_weight",
        "final_score"
    ]
].head(20)

,course_code,course_title,university,openai_aims_score,openai_content_score,openai_outcomes_score,available_weight,final_score
878,COMM 392,Introduction to Data Management and Analytics ...,Queen's University,0.758155,NaN,NaN,0.40,0.758155
214,INFO260,Data Management,University of Canterbury,0.731719,NaN,NaN,0.40,0.731719
895,COMM 461,Data Science for Business,Queen's University,0.698917,NaN,NaN,0.40,0.698917
215,INFO261,Introduction to Business Analytics,University of Canterbury,0.672088,NaN,0.636934,0.65,0.658567
220,INFO361,Business Intelligence and Analytics,University of Canterbury,0.641752,NaN,NaN,0.40,0.641752
558,ISOM3360,Data Mining for Business Analytics,The Hong Kong University of Science and Techno...,0.663187,NaN,0.549724,0.65,0.619547
427,ACCT4710,Accounting Analytics for Professional Accountants,The Hong Kong University of Science and Techno...,0.636578,NaN,0.548004,0.65,0.602511
680,COMP4332,Big Data Mining and Management,The Hong Kong University of Science and Techno...,0.647407,NaN,0.514817,0.65,0.596411
163,DATA201,Data Wrangling,University of Canterbury,0.590257,NaN,NaN,0.40,0.590257
545,ISOM2600,Introduction to Business Analytics,The Hong Kong University of Science and Techno...,0.643160,NaN,0.495821,0.65,0.586491
607,RMBI1020,Business Intelligence for Data-Driven Decisions,The Hong Kong University of Science and Techno...,0.655140,NaN,0.474887,0.65,0.585812
893,COMM 433,Marketing Analytics,Queen's University,0.582864,NaN,NaN,0.40,0.582864
218,INFO343,IT Governance and Strategy,University of Canterbury,0.577399,NaN,NaN,0.40,0.577399
631,DASC2210,A Survey on Big Data in Science and Society,The Hong Kong University of Science and Techno...,0.612604,NaN,0.519420,0.65,0.576764
507,MARK3620,Marketing Analytics,The Hong Kong University of Science and Techno...,0.639175,NaN,0.474750,0.65,0.575935
831,COMM 190,Introduction to Digital Business and Technologies,Queen's University,0.575376,NaN,NaN,0.40,0.575376
277,MGMT374,Operations and Supply Chain Analytics,University of Canterbury,0.572459,NaN,NaN,0.40,0.572459
614,RMBI4310,Advanced Data Mining for Risk Management and B...,The Hong Kong University of Science and Techno...,0.568453,NaN,0.574518,0.65,0.570786
638,DASC4020,Structured Query Language for Data Analytics,The Hong Kong University of Science and Techno...,0.595625,NaN,0.529579,0.65,0.570223
649,COMP1942,Exploring and Visualizing Data,The Hong Kong University of Science and Techno...,0.597319,NaN,0.524639,0.65,0.569365

In [115]:
results.sort_values(
    "final_score",
    ascending=False
)[
    [
        "course_code",
        "course_title",
        "openai_aims_score",
        "openai_content_score",
        "openai_outcomes_score",
        "available_weight",
        "final_score"
    ]
].head(30)

,course_code,course_title,openai_aims_score,openai_content_score,openai_outcomes_score,available_weight,final_score
878,COMM 392,Introduction to Data Management and Analytics ...,0.758155,NaN,NaN,0.40,0.758155
214,INFO260,Data Management,0.731719,NaN,NaN,0.40,0.731719
895,COMM 461,Data Science for Business,0.698917,NaN,NaN,0.40,0.698917
215,INFO261,Introduction to Business Analytics,0.672088,NaN,0.636934,0.65,0.658567
220,INFO361,Business Intelligence and Analytics,0.641752,NaN,NaN,0.40,0.641752
558,ISOM3360,Data Mining for Business Analytics,0.663187,NaN,0.549724,0.65,0.619547
427,ACCT4710,Accounting Analytics for Professional Accountants,0.636578,NaN,0.548004,0.65,0.602511
680,COMP4332,Big Data Mining and Management,0.647407,NaN,0.514817,0.65,0.596411
163,DATA201,Data Wrangling,0.590257,NaN,NaN,0.40,0.590257
545,ISOM2600,Introduction to Business Analytics,0.643160,NaN,0.495821,0.65,0.586491
607,RMBI1020,Business Intelligence for Data-Driven Decisions,0.655140,NaN,0.474887,0.65,0.585812
893,COMM 433,Marketing Analytics,0.582864,NaN,NaN,0.40,0.582864
218,INFO343,IT Governance and Strategy,0.577399,NaN,NaN,0.40,0.577399
631,DASC2210,A Survey on Big Data in Science and Society,0.612604,NaN,0.519420,0.65,0.576764
507,MARK3620,Marketing Analytics,0.639175,NaN,0.474750,0.65,0.575935
831,COMM 190,Introduction to Digital Business and Technologies,0.575376,NaN,NaN,0.40,0.575376
277,MGMT374,Operations and Supply Chain Analytics,0.572459,NaN,NaN,0.40,0.572459
614,RMBI4310,Advanced Data Mining for Risk Management and B...,0.568453,NaN,0.574518,0.65,0.570786
638,DASC4020,Structured Query Language for Data Analytics,0.595625,NaN,0.529579,0.65,0.570223
649,COMP1942,Exploring and Visualizing Data,0.597319,NaN,0.524639,0.65,0.569365
592,ISOM4860,Decision and Data Analytics in Financial Markets,0.608289,NaN,0.504350,0.65,0.568313
559,ISOM3370,Big Data Technologies,0.614912,NaN,0.461100,0.65,0.555754
639,DASC4300,Capstone Project for Data Analytics in Science,0.551764,NaN,0.556175,0.65,0.553461
5,EBA 3630,Data Driven Management Accounting,0.575792,0.573533,0.488051,1.00,0.553066
532,MGMT4290,HR Analytics,0.547770,NaN,0.549727,0.65,0.548523
315,BUST08032,Business Analytics and Information Systems,0.514690,0.632385,0.483854,1.00,0.548174
492,FINA4713,Introduction to Artificial Intelligence and Bi...,0.567377,NaN,0.509225,0.65,0.545011
555,ISOM3330,Data Visualization and Visual Analytics,0.548446,NaN,0.518492,0.65,0.536925
551,ISOM3260,Database Design and Administration,0.551972,NaN,0.511630,0.65,0.536456
166,DATA303,Computational Data Methods,0.534957,NaN,NaN,0.40,0.534957

In [116]:
results_complete = results[
    (results["available_weight"] == 1.0)
]

results_complete.sort_values(
    "final_score",
    ascending=False
)[
    [
        "course_code",
        "course_title",
        "openai_aims_score",
        "openai_content_score",
        "openai_outcomes_score",
        "final_score"
    ]
].head(20)

,course_code,course_title,openai_aims_score,openai_content_score,openai_outcomes_score,final_score
5,EBA 3630,Data Driven Management Accounting,0.575792,0.573533,0.488051,0.553066
315,BUST08032,Business Analytics and Information Systems,0.514690,0.632385,0.483854,0.548174
52,GRA 2269,Leading in Organizations Using Intelligent Dec...,0.566667,0.494310,0.512697,0.527850
9,EDI 3510,Business Information Systems,0.566226,0.508026,0.422313,0.509878
115,TEM 0056,Applied Data Analytics,0.653757,0.383777,0.430964,0.503566
58,GRA 4137,Data Protection and Ethics in the Modern Busin...,0.568707,0.463886,0.451255,0.502657
365,BUST10145,Predictive Analytics for Business,0.478578,0.472222,0.567909,0.498686
798,ADM-12350,Data-driven business decisions,0.622188,0.412467,0.416186,0.497285
373,BUST10159,The Strategy of Digital Transformation,0.504358,0.529203,0.439358,0.496804
96,TEM 0241,AI for Business,0.474669,0.512872,0.501811,0.494825
363,BUST10092,Operations Strategy,0.486241,0.518740,0.452971,0.489298
318,BUST08033,Business Research Methods I: Introduction to D...,0.488750,0.468987,0.471994,0.477644
330,BUST08045,Thinking about Business,0.548328,0.436909,0.421250,0.477562
329,BUST08057,Strategic Marketing Insights,0.445933,0.522947,0.452078,0.474424
367,BUST10142,Service Management in an International Context,0.499799,0.429523,0.494936,0.473987
93,TEM 0480,Operational Planning and Logistics Analytics,0.564916,0.394093,0.438745,0.473585
108,TEM 0521,Agile Management and Collaborative Leadership,0.462952,0.476129,0.476210,0.470878
357,BUST10107,Managing Change,0.464099,0.455912,0.490157,0.467748
361,BUST10134,Mathematical Programming in Advanced Analytics,0.493240,0.498903,0.380162,0.466953
340,BUST10144,Digital Business,0.498793,0.457578,0.428063,0.466685